import 'dart:convert';
import 'dart:math';
import 'package:flutter/foundation.dart';
import 'package:http/http.dart' as http;
import 'onboarding_data_service.dart';
import 'postcode_service.dart';
import 'meetup_service.dart';
import 'default_group_service.dart';

// =============================================================================
// AI MEETUP MATCHMAKER SERVICE
// Uses Gemini AI to generate personalised meetup suggestions and
// intelligent compatibility reasoning between parents
// =============================================================================

/// A parent profile used for matching
class MatchableParent {
  final String id;
  final String name;
  final String? avatarUrl;
  final String? borough;
  final List<String> stagesOfLife;
  final List<String> childAges;
  final List<String> groupIds;
  final List<String> interests;
  final double compatibilityScore;

  const MatchableParent({
    required this.id,
    required this.name,
    this.avatarUrl,
    this.borough,
    this.stagesOfLife = const [],
    this.childAges = const [],
    this.groupIds = const [],
    this.interests = const [],
    this.compatibilityScore = 0.0,
  });

  MatchableParent copyWith({double? compatibilityScore}) => MatchableParent(
        id: id,
        name: name,
        avatarUrl: avatarUrl,
        borough: borough,
        stagesOfLife: stagesOfLife,
        childAges: childAges,
        groupIds: groupIds,
        interests: interests,
        compatibilityScore: compatibilityScore ?? this.compatibilityScore,
      );
}

/// A suggested meetup generated by the AI matchmaker
class SuggestedMeetup {
  final String id;
  final String title;
  final String description;
  final String category;
  final String suggestedLocation;
  final String suggestedDate;
  final String suggestedTime;
  final DateTime suggestedDateTime;
  final List<MatchableParent> matchedParents;
  final double confidenceScore;
  final String reasoning;
  final String? weatherNote;
  final String iconEmoji;

  const SuggestedMeetup({
    required this.id,
    required this.title,
    required this.description,
    required this.category,
    required this.suggestedLocation,
    required this.suggestedDate,
    required this.suggestedTime,
    required this.suggestedDateTime,
    required this.matchedParents,
    required this.confidenceScore,
    required this.reasoning,
    this.weatherNote,
    required this.iconEmoji,
  });
}

class AiMatchmakerService {
  static final AiMatchmakerService _instance =
      AiMatchmakerService._internal();
  factory AiMatchmakerService() => _instance;
  AiMatchmakerService._internal();

  final OnboardingDataService _onboarding = OnboardingDataService();
  final PostcodeService _postcode = PostcodeService();
  final MeetupService _meetupService = MeetupService();
  final DefaultGroupService _groupService = DefaultGroupService();

  // Gemini API configuration
  static const String _geminiApiKey =
      'AIzaSyA3MOqpbEWR5shMm1EF6H06-O5mGVyxqIg';
  static const String _geminiModel = 'gemini-2.0-flash';
  static const String _geminiBaseUrl =
      'https://generativelanguage.googleapis.com/v1beta/models';

  List<SuggestedMeetup> _suggestions = [];
  List<MatchableParent> _nearbyParents = [];
  bool _isInitialized = false;

  List<SuggestedMeetup> get suggestions => List.unmodifiable(_suggestions);
  List<MatchableParent> get nearbyParents => List.unmodifiable(_nearbyParents);

  Future<void> initialize() async {
    if (_isInitialized) return;
    await _onboarding.initialize();
    await _groupService.initialize();
    _generateNearbyParents();
    await _generateSuggestions();
    _isInitialized = true;
  }

  Future<void> refresh() async {
    _generateNearbyParents();
    await _generateSuggestions();
  }

  // ── Generate simulated nearby parents ──────────────────────────────────
  void _generateNearbyParents() {
    final borough = _getUserBorough();
    final userStages = _onboarding.stagesOfLife;

    final parentProfiles = <MatchableParent>[
      MatchableParent(
        id: 'match_1', name: 'Sophie Williams',
        avatarUrl: 'https://i.pravatar.cc/150?img=1',
        borough: borough, stagesOfLife: ['parent'],
        childAges: ['8 months'],
        groupIds: ['disc_new_parents', 'disc_baby_sensory'],
        interests: ['Coffee mornings', 'Baby sensory', 'Pram walks'],
      ),
      MatchableParent(
        id: 'match_2', name: 'Emma Thompson',
        avatarUrl: 'https://i.pravatar.cc/150?img=5',
        borough: borough, stagesOfLife: ['parent'],
        childAges: ['14 months', '3 years'],
        groupIds: ['disc_toddler_group', 'disc_playdate_club'],
        interests: ['Playdates', 'Parks', 'Soft play'],
      ),
      MatchableParent(
        id: 'match_3', name: 'James Carter',
        avatarUrl: 'https://i.pravatar.cc/150?img=12',
        borough: borough, stagesOfLife: ['parent'],
        childAges: ['2 years'],
        groupIds: ['disc_dads_connect', 'disc_sports_parents'],
        interests: ['Golf', 'Football', 'Dad meetups'],
      ),
      MatchableParent(
        id: 'match_4', name: 'Anna Mitchell',
        avatarUrl: 'https://i.pravatar.cc/150?img=9',
        borough: borough, stagesOfLife: ['expecting'],
        childAges: [],
        groupIds: ['disc_expecting_parents'],
        interests: ['Pregnancy yoga', 'Birth prep', 'Antenatal'],
      ),
      MatchableParent(
        id: 'match_5', name: 'Kate Rogers',
        avatarUrl: 'https://i.pravatar.cc/150?img=16',
        borough: borough, stagesOfLife: ['parent'],
        childAges: ['6 months'],
        groupIds: ['disc_new_parents', 'disc_breastfeeding'],
        interests: ['Coffee mornings', 'Swimming', 'Music classes'],
      ),
      MatchableParent(
        id: 'match_6', name: 'Lucy Taylor',
        avatarUrl: 'https://i.pravatar.cc/150?img=20',
        borough: borough, stagesOfLife: ['parent'],
        childAges: ['18 months'],
        groupIds: ['disc_toddler_group', 'disc_nature_walks'],
        interests: ['Nature walks', 'Messy play', 'Cooking for kids'],
      ),
      MatchableParent(
        id: 'match_7', name: 'Mark Robinson',
        avatarUrl: 'https://i.pravatar.cc/150?img=33',
        borough: borough, stagesOfLife: ['parent'],
        childAges: ['4 years'],
        groupIds: ['disc_dads_connect', 'disc_school_ready'],
        interests: ['Cycling', 'Science activities', 'STEM toys'],
      ),
      MatchableParent(
        id: 'match_8', name: 'Sarah Clarke',
        avatarUrl: 'https://i.pravatar.cc/150?img=23',
        borough: borough, stagesOfLife: ['parent'],
        childAges: ['10 months', '5 years'],
        groupIds: ['disc_new_parents', 'disc_school_ready'],
        interests: ['After-school activities', 'Parks', 'Baking'],
      ),
    ];

    _nearbyParents = parentProfiles.map((parent) {
      final score = _calculateCompatibility(parent, userStages);
      return parent.copyWith(compatibilityScore: score);
    }).toList()
      ..sort((a, b) => b.compatibilityScore.compareTo(a.compatibilityScore));
  }

  // ── Compatibility scoring algorithm ────────────────────────────────────
  double _calculateCompatibility(
      MatchableParent parent, List<String> userStages) {
    double score = 0.0;
    final userChildren = _onboarding.children;
    final userGroups =
        _groupService.getAllDefaultGroups().map((g) => g.id).toList();

    if (parent.borough == _getUserBorough()) score += 0.30;

    if (userChildren.isNotEmpty && parent.childAges.isNotEmpty) {
      for (final childMap in userChildren) {
        final birthday = childMap['birthday'];
        if (birthday != null) {
          final childAge = _parseChildAgeMonths(birthday);
          for (final parentChildAge in parent.childAges) {
            final parentAge = _parseAgeStringToMonths(parentChildAge);
            final ageDiff = (childAge - parentAge).abs();
            if (ageDiff <= 3) {
              score += 0.25;
              break;
            } else if (ageDiff <= 6) {
              score += 0.18;
              break;
            } else if (ageDiff <= 12) {
              score += 0.10;
              break;
            }
          }
        }
      }
    } else if (userStages.isNotEmpty && parent.stagesOfLife.isNotEmpty) {
      final overlap =
          userStages.where((s) => parent.stagesOfLife.contains(s)).length;
      score += (overlap / max(1, userStages.length)) * 0.25;
    }

    if (userGroups.isNotEmpty && parent.groupIds.isNotEmpty) {
      final sharedGroups =
          userGroups.where((g) => parent.groupIds.contains(g)).length;
      score += (sharedGroups / max(1, parent.groupIds.length)) * 0.25;
    }

    final goingMeetups =
        _meetupService.meetups.where((m) => m.isGoing).toList();
    if (goingMeetups.isNotEmpty) {
      final sharedMeetups = goingMeetups
          .where((m) => m.attendeeNames
              .any((name) => parent.name.startsWith(name.split(' ').first)))
          .length;
      score += (sharedMeetups / max(1, goingMeetups.length)) * 0.20;
    } else {
      score += 0.08;
    }

    return score.clamp(0.0, 1.0);
  }

  // ── AI-powered suggestion generation ──────────────────────────────────
  Future<void> _generateSuggestions() async {
    final now = DateTime.now();
    final borough = _getUserBorough();
    final userStages = _onboarding.stagesOfLife;
    final userName = _onboarding.name ?? 'there';
    final userChildren = _onboarding.children;
    final topMatches = _nearbyParents.take(6).toList();

    // Try Gemini AI first for suggestion descriptions
    Map<String, dynamic>? aiSuggestions;
    try {
      aiSuggestions = await _getAiSuggestions(
        userName,
        borough,
        userStages,
        userChildren,
        topMatches,
      );
    } catch (e) {
      if (kDebugMode) {
        debugPrint('AI matchmaker suggestion error: $e');
      }
    }

    final rng = Random(now.day + now.month);
    final isWinterish = now.month >= 11 || now.month <= 2;
    final isRainy = rng.nextDouble() > 0.6;

    _suggestions = [];

    // Extract AI suggestions or use enhanced fallback
    final aiMeetups =
        (aiSuggestions?['meetups'] as List<dynamic>?) ?? [];

    // Suggestion 1: Age-matched playdate
    if (userChildren.isNotEmpty || userStages.contains('parent')) {
      final playMatches = topMatches
          .where((p) => p.interests.any((i) =>
              i.toLowerCase().contains('play') ||
              i.toLowerCase().contains('park')))
          .take(4)
          .toList();

      if (playMatches.isNotEmpty) {
        final sugDate = _nextWeekday(now, DateTime.saturday);
        final aiData = aiMeetups.isNotEmpty
            ? aiMeetups[0] as Map<String, dynamic>?
            : null;

        _suggestions.add(SuggestedMeetup(
          id: 'sug_1',
          title: aiData?['title'] as String? ??
              (isRainy ? 'Soft Play Session' : 'Playdate at the Park'),
          description: aiData?['description'] as String? ??
              '${playMatches.length} parents with similar-aged kids nearby. Great match for your family!',
          category: 'Playdate',
          suggestedLocation: isRainy
              ? 'Tumble Town Soft Play, $borough'
              : 'Cherry Hinton Hall, $borough',
          suggestedDate: _formatDate(sugDate),
          suggestedTime: '10:00 \u2013 11:30 AM',
          suggestedDateTime:
              DateTime(sugDate.year, sugDate.month, sugDate.day, 10, 0),
          matchedParents: playMatches,
          confidenceScore: 0.92,
          reasoning: aiData?['reasoning'] as String? ??
              'Based on your children\'s ages and ${playMatches.length} nearby parents with kids in the same age range',
          weatherNote: isRainy
              ? 'Rain expected \u2014 indoor venue recommended'
              : isWinterish
                  ? 'Chilly but dry \u2014 wrap up warm!'
                  : 'Lovely weather forecast \u2014 perfect for outdoors!',
          iconEmoji: '\u{1F3DD}',
        ));
      }
    }

    // Suggestion 2: Coffee morning
    final coffeeMatches = topMatches
        .where((p) =>
            p.interests.any((i) => i.toLowerCase().contains('coffee')) ||
            p.childAges.any((a) => _parseAgeStringToMonths(a) <= 12))
        .take(5)
        .toList();

    if (coffeeMatches.isNotEmpty) {
      final sugDate = _nextWeekday(now, DateTime.wednesday);
      final aiData = aiMeetups.length > 1
          ? aiMeetups[1] as Map<String, dynamic>?
          : null;

      _suggestions.add(SuggestedMeetup(
        id: 'sug_2',
        title: aiData?['title'] as String? ?? 'Coffee & Chat \u2014 New Parents',
        description: aiData?['description'] as String? ??
            '${coffeeMatches.length} parents near you are keen on coffee mornings. Meet in a relaxed setting.',
        category: 'Coffee',
        suggestedLocation: 'Little Bean Cafe, $borough',
        suggestedDate: _formatDate(sugDate),
        suggestedTime: '9:30 \u2013 11:00 AM',
        suggestedDateTime:
            DateTime(sugDate.year, sugDate.month, sugDate.day, 9, 30),
        matchedParents: coffeeMatches,
        confidenceScore: 0.88,
        reasoning: aiData?['reasoning'] as String? ??
            '${coffeeMatches.length} parents within walking distance are interested in coffee meetups',
        iconEmoji: '\u2615',
      ));
    }

    // Suggestion 3: Active / outdoors meetup
    final walkMatches = topMatches
        .where((p) => p.interests.any((i) =>
            i.toLowerCase().contains('walk') ||
            i.toLowerCase().contains('nature') ||
            i.toLowerCase().contains('cycling')))
        .take(4)
        .toList();

    if (walkMatches.isNotEmpty) {
      final sugDate = _nextWeekday(now, DateTime.friday);
      final aiData = aiMeetups.length > 2
          ? aiMeetups[2] as Map<String, dynamic>?
          : null;

      _suggestions.add(SuggestedMeetup(
        id: 'sug_3',
        title: aiData?['title'] as String? ??
            (isWinterish ? 'Winter Pram Walk' : 'Pram Walk & Picnic'),
        description: aiData?['description'] as String? ??
            '${walkMatches.length} active parents nearby enjoy outdoor walks. Fresh air and friendship!',
        category: 'Walk',
        suggestedLocation: 'Jesus Green, $borough',
        suggestedDate: _formatDate(sugDate),
        suggestedTime: '10:00 AM \u2013 12:00 PM',
        suggestedDateTime:
            DateTime(sugDate.year, sugDate.month, sugDate.day, 10, 0),
        matchedParents: walkMatches,
        confidenceScore: 0.85,
        reasoning: aiData?['reasoning'] as String? ??
            'Matched ${walkMatches.length} parents who enjoy outdoor activities in your area',
        weatherNote: isRainy
            ? 'Rain expected \u2014 consider moving indoors'
            : 'Lovely weather forecast!',
        iconEmoji: '\u{1F6B6}',
      ));
    }

    // Suggestion 4: Dads-only meetup
    if (_onboarding.parentType == 'dad') {
      final dadMatches = topMatches
          .where((p) => p.groupIds.any((g) => g.contains('dad')))
          .take(4)
          .toList();

      if (dadMatches.isNotEmpty) {
        final sugDate = _nextWeekday(now, DateTime.sunday);
        final aiData = aiMeetups.length > 3
            ? aiMeetups[3] as Map<String, dynamic>?
            : null;

        _suggestions.add(SuggestedMeetup(
          id: 'sug_4',
          title: aiData?['title'] as String? ?? 'Dad\'s Sunday Brunch',
          description: aiData?['description'] as String? ??
              'Connect with ${dadMatches.length} local dads over brunch. Kids welcome!',
          category: 'Social',
          suggestedLocation: 'The Ivy Cafe, $borough',
          suggestedDate: _formatDate(sugDate),
          suggestedTime: '10:00 \u2013 12:00 PM',
          suggestedDateTime:
              DateTime(sugDate.year, sugDate.month, sugDate.day, 10, 0),
          matchedParents: dadMatches,
          confidenceScore: 0.90,
          reasoning: aiData?['reasoning'] as String? ??
              'You\'re a dad \u2014 these ${dadMatches.length} dads are in your groups and live nearby',
          iconEmoji: '\u{1F468}\u200D\u{1F467}',
        ));
      }
    }

    // Suggestion 5: Expecting parents meetup
    if (userStages.contains('expecting')) {
      final expectingMatches = topMatches
          .where((p) => p.stagesOfLife.contains('expecting'))
          .take(3)
          .toList();

      if (expectingMatches.isNotEmpty) {
        final sugDate = _nextWeekday(now, DateTime.thursday);
        _suggestions.add(SuggestedMeetup(
          id: 'sug_5',
          title: 'Expecting Parents Tea',
          description:
              '${expectingMatches.length} parents-to-be near you. Share tips, ask questions, and make friends before baby arrives!',
          category: 'Social',
          suggestedLocation: 'Community Centre, $borough',
          suggestedDate: _formatDate(sugDate),
          suggestedTime: '2:00 \u2013 3:30 PM',
          suggestedDateTime:
              DateTime(sugDate.year, sugDate.month, sugDate.day, 14, 0),
          matchedParents: expectingMatches,
          confidenceScore: 0.93,
          reasoning:
              'You\'re expecting \u2014 meet ${expectingMatches.length} other parents-to-be in your borough',
          iconEmoji: '\u{1F930}',
        ));
      }
    }

    // Always add a general social suggestion
    final sugDate = _nextWeekday(now, DateTime.saturday, weeksAhead: 1);
    final aiData = aiMeetups.length > 4
        ? aiMeetups[4] as Map<String, dynamic>?
        : null;

    _suggestions.add(SuggestedMeetup(
      id: 'sug_general',
      title: aiData?['title'] as String? ??
          'Friday Night Dinner \u2014 Parents Only!',
      description: aiData?['description'] as String? ??
          'Leave the kids with a babysitter and enjoy an adults-only evening. ${topMatches.length} parents nearby are up for it!',
      category: 'Social',
      suggestedLocation: 'Trattoria Roma, Mill Road, $borough',
      suggestedDate: _formatDate(sugDate),
      suggestedTime: '7:00 \u2013 10:00 PM',
      suggestedDateTime:
          DateTime(sugDate.year, sugDate.month, sugDate.day, 19, 0),
      matchedParents: topMatches.take(4).toList(),
      confidenceScore: 0.80,
      reasoning: aiData?['reasoning'] as String? ??
          'Everyone needs a night out! ${topMatches.length} active parents in your community',
      iconEmoji: '\u{1F37D}',
    ));

    _suggestions.sort((a, b) => b.confidenceScore.compareTo(a.confidenceScore));
  }

  /// Call Gemini API to generate personalised meetup suggestions
  Future<Map<String, dynamic>> _getAiSuggestions(
    String userName,
    String borough,
    List<String> userStages,
    List<Map<String, String>> userChildren,
    List<MatchableParent> topMatches,
  ) async {
    final childContext = StringBuffer();
    for (final child in userChildren) {
      final name = child['name'] ?? 'Child';
      final birthday = child['birthday'];
      if (birthday != null) {
        final months = _parseChildAgeMonths(birthday);
        childContext.writeln('- $name: ${months < 12 ? "$months months" : "${months ~/ 12} years"} old');
      }
    }

    final matchContext = topMatches
        .take(4)
        .map((p) =>
            '${p.name} (${p.childAges.join(", ")}, interests: ${p.interests.join(", ")})')
        .join('\n');

    final systemPrompt = '''You are the huddl AI Matchmaker for a UK parents' community app. Generate personalised meetup suggestions based on parent compatibility.

RESPOND IN EXACT JSON FORMAT (no markdown, no backticks, just raw JSON):
{
  "meetups": [
    {
      "title": "Creative meetup title",
      "description": "2-3 sentence engaging description that mentions specific matched parents and why they'd get along",
      "reasoning": "1 sentence explaining the AI matching logic"
    }
  ]
}

Generate exactly 5 meetup suggestions. Use British English. Be warm, specific and mention real parent names from the matches.''';

    final requestBody = {
      'system_instruction': {
        'parts': [
          {'text': systemPrompt}
        ]
      },
      'contents': [
        {
          'role': 'user',
          'parts': [
            {
              'text': '''Generate meetup suggestions for $userName in $borough.

User's stages: ${userStages.join(', ')}
User's children:
${childContext.isNotEmpty ? childContext.toString() : 'No children info'}
Parent type: ${_onboarding.parentType ?? 'parent'}

Top compatible parents nearby:
$matchContext

Please suggest 5 diverse meetups: 1) playdate, 2) coffee morning, 3) outdoor activity, 4) social evening, 5) themed meetup.'''
            }
          ]
        }
      ],
      'generationConfig': {
        'temperature': 0.85,
        'topP': 0.95,
        'maxOutputTokens': 1024,
      },
    };

    final url = Uri.parse(
        '$_geminiBaseUrl/$_geminiModel:generateContent?key=$_geminiApiKey');

    final response = await http
        .post(
          url,
          headers: {'Content-Type': 'application/json'},
          body: jsonEncode(requestBody),
        )
        .timeout(const Duration(seconds: 15));

    if (response.statusCode == 200) {
      final data = jsonDecode(response.body);
      final candidates = data['candidates'] as List?;
      if (candidates != null && candidates.isNotEmpty) {
        final content = candidates[0]['content'];
        final parts = content['parts'] as List?;
        if (parts != null && parts.isNotEmpty) {
          var text = (parts[0]['text'] as String? ?? '').trim();
          text = text.replaceAll(RegExp(r'^```json\s*'), '');
          text = text.replaceAll(RegExp(r'\s*```$'), '');
          text = text.trim();
          return jsonDecode(text) as Map<String, dynamic>;
        }
      }
    }

    throw Exception('No valid AI response');
  }

  /// Convert a suggestion into a real Meetup
  Meetup createMeetupFromSuggestion(SuggestedMeetup suggestion) {
    final meetup = Meetup(
      id: 'mu_ai_${DateTime.now().millisecondsSinceEpoch}',
      title: suggestion.title,
      description: suggestion.description,
      category: suggestion.category,
      dateDisplay: suggestion.suggestedDate,
      timeDisplay: suggestion.suggestedTime,
      dateTime: suggestion.suggestedDateTime,
      location: suggestion.suggestedLocation,
      organiserName: _onboarding.name ?? 'You',
      organiserId: 'current_user',
      attendeeCount: 1,
      isGoing: true,
      attendeeNames: [_onboarding.name ?? 'You'],
      isFree: true,
      borough: _getUserBorough(),
      privacy: MeetupPrivacy.public,
      invitees: suggestion.matchedParents
          .map((p) => MeetupAttendee(
                id: p.id,
                name: p.name,
                avatarUrl: p.avatarUrl,
                status: 'invited',
              ))
          .toList(),
    );

    _meetupService.createMeetup(meetup);
    return meetup;
  }

  // ── Helpers ────────────────────────────────────────────────────────────
  String _getUserBorough() {
    final pc = _onboarding.postcode;
    if (pc != null) {
      return _postcode.getBoroughFromPostcode(pc) ?? 'Cambridge';
    }
    return 'Cambridge';
  }

  int _parseChildAgeMonths(String birthday) {
    try {
      final parts = birthday.split('/');
      if (parts.length >= 2) {
        final month = int.parse(parts[0]);
        final year = int.parse(parts.last);
        final now = DateTime.now();
        final birth = DateTime(year, month);
        return ((now.difference(birth).inDays) / 30.44).round();
      }
    } catch (_) {}
    return 24;
  }

  int _parseAgeStringToMonths(String ageStr) {
    final lower = ageStr.toLowerCase();
    final numMatch = RegExp(r'(\d+)').firstMatch(lower);
    if (numMatch == null) return 24;
    final num = int.parse(numMatch.group(1)!);
    if (lower.contains('year')) return num * 12;
    return num;
  }

  DateTime _nextWeekday(DateTime from, int weekday, {int weeksAhead = 0}) {
    var d = from.add(Duration(days: 1 + weeksAhead * 7));
    while (d.weekday != weekday) {
      d = d.add(const Duration(days: 1));
    }
    return d;
  }

  String _formatDate(DateTime d) {
    const dayAbbr = ['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN'];
    const monthAbbr = [
      'JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN',
      'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC'
    ];
    return '${dayAbbr[d.weekday - 1]}, ${monthAbbr[d.month - 1]} ${d.day}';
  }
}
