import 'dart:math';
import 'onboarding_data_service.dart';
import 'postcode_service.dart';
import 'meetup_service.dart';
import 'default_group_service.dart';

// ═══════════════════════════════════════════════════════════════════════════════
// AI MEETUP MATCHMAKER SERVICE
// Scores compatibility between parents and suggests optimal meetups
// ═══════════════════════════════════════════════════════════════════════════════

/// A parent profile used for matching
class MatchableParent {
  final String id;
  final String name;
  final String? avatarUrl;
  final String? borough;
  final List<String> stagesOfLife;
  final List<String> childAges; // e.g. "14 months", "3 years"
  final List<String> groupIds;
  final List<String> interests;
  final double compatibilityScore;

  const MatchableParent({
    required this.id,
    required this.name,
    this.avatarUrl,
    this.borough,
    this.stagesOfLife = const [],
    this.childAges = const [],
    this.groupIds = const [],
    this.interests = const [],
    this.compatibilityScore = 0.0,
  });

  MatchableParent copyWith({double? compatibilityScore}) => MatchableParent(
    id: id,
    name: name,
    avatarUrl: avatarUrl,
    borough: borough,
    stagesOfLife: stagesOfLife,
    childAges: childAges,
    groupIds: groupIds,
    interests: interests,
    compatibilityScore: compatibilityScore ?? this.compatibilityScore,
  );
}

/// A suggested meetup generated by the AI matchmaker
class SuggestedMeetup {
  final String id;
  final String title;
  final String description;
  final String category;
  final String suggestedLocation;
  final String suggestedDate;
  final String suggestedTime;
  final DateTime suggestedDateTime;
  final List<MatchableParent> matchedParents;
  final double confidenceScore; // 0.0 to 1.0
  final String reasoning;
  final String? weatherNote;
  final String iconEmoji;

  const SuggestedMeetup({
    required this.id,
    required this.title,
    required this.description,
    required this.category,
    required this.suggestedLocation,
    required this.suggestedDate,
    required this.suggestedTime,
    required this.suggestedDateTime,
    required this.matchedParents,
    required this.confidenceScore,
    required this.reasoning,
    this.weatherNote,
    required this.iconEmoji,
  });
}

class AiMatchmakerService {
  static final AiMatchmakerService _instance = AiMatchmakerService._internal();
  factory AiMatchmakerService() => _instance;
  AiMatchmakerService._internal();

  final OnboardingDataService _onboarding = OnboardingDataService();
  final PostcodeService _postcode = PostcodeService();
  final MeetupService _meetupService = MeetupService();
  final DefaultGroupService _groupService = DefaultGroupService();

  List<SuggestedMeetup> _suggestions = [];
  List<MatchableParent> _nearbyParents = [];
  bool _isInitialized = false;

  List<SuggestedMeetup> get suggestions => List.unmodifiable(_suggestions);
  List<MatchableParent> get nearbyParents => List.unmodifiable(_nearbyParents);

  Future<void> initialize() async {
    if (_isInitialized) return;
    await _onboarding.initialize();
    await _groupService.initialize();
    _generateNearbyParents();
    _generateSuggestions();
    _isInitialized = true;
  }

  void refresh() {
    _generateNearbyParents();
    _generateSuggestions();
  }

  // ── Generate simulated nearby parents ──────────────────────────────────
  void _generateNearbyParents() {
    final borough = _getUserBorough();
    final userStages = _onboarding.stagesOfLife;

    final parentProfiles = <MatchableParent>[
      MatchableParent(
        id: 'match_1', name: 'Sophie Williams',
        avatarUrl: 'https://i.pravatar.cc/150?img=1',
        borough: borough,
        stagesOfLife: ['parent'],
        childAges: ['8 months'],
        groupIds: ['disc_new_parents', 'disc_baby_sensory'],
        interests: ['Coffee mornings', 'Baby sensory', 'Pram walks'],
      ),
      MatchableParent(
        id: 'match_2', name: 'Emma Thompson',
        avatarUrl: 'https://i.pravatar.cc/150?img=5',
        borough: borough,
        stagesOfLife: ['parent'],
        childAges: ['14 months', '3 years'],
        groupIds: ['disc_toddler_group', 'disc_playdate_club'],
        interests: ['Playdates', 'Parks', 'Soft play'],
      ),
      MatchableParent(
        id: 'match_3', name: 'James Carter',
        avatarUrl: 'https://i.pravatar.cc/150?img=12',
        borough: borough,
        stagesOfLife: ['parent'],
        childAges: ['2 years'],
        groupIds: ['disc_dads_connect', 'disc_sports_parents'],
        interests: ['Golf', 'Football', 'Dad meetups'],
      ),
      MatchableParent(
        id: 'match_4', name: 'Anna Mitchell',
        avatarUrl: 'https://i.pravatar.cc/150?img=9',
        borough: borough,
        stagesOfLife: ['expecting'],
        childAges: [],
        groupIds: ['disc_expecting_parents'],
        interests: ['Pregnancy yoga', 'Birth prep', 'Antenatal'],
      ),
      MatchableParent(
        id: 'match_5', name: 'Kate Rogers',
        avatarUrl: 'https://i.pravatar.cc/150?img=16',
        borough: borough,
        stagesOfLife: ['parent'],
        childAges: ['6 months'],
        groupIds: ['disc_new_parents', 'disc_breastfeeding'],
        interests: ['Coffee mornings', 'Swimming', 'Music classes'],
      ),
      MatchableParent(
        id: 'match_6', name: 'Lucy Taylor',
        avatarUrl: 'https://i.pravatar.cc/150?img=20',
        borough: borough,
        stagesOfLife: ['parent'],
        childAges: ['18 months'],
        groupIds: ['disc_toddler_group', 'disc_nature_walks'],
        interests: ['Nature walks', 'Messy play', 'Cooking for kids'],
      ),
      MatchableParent(
        id: 'match_7', name: 'Mark Robinson',
        avatarUrl: 'https://i.pravatar.cc/150?img=33',
        borough: borough,
        stagesOfLife: ['parent'],
        childAges: ['4 years'],
        groupIds: ['disc_dads_connect', 'disc_school_ready'],
        interests: ['Cycling', 'Science activities', 'STEM toys'],
      ),
      MatchableParent(
        id: 'match_8', name: 'Sarah Clarke',
        avatarUrl: 'https://i.pravatar.cc/150?img=23',
        borough: borough,
        stagesOfLife: ['parent'],
        childAges: ['10 months', '5 years'],
        groupIds: ['disc_new_parents', 'disc_school_ready'],
        interests: ['After-school activities', 'Parks', 'Baking'],
      ),
    ];

    // Score each parent
    _nearbyParents = parentProfiles.map((parent) {
      final score = _calculateCompatibility(parent, userStages);
      return parent.copyWith(compatibilityScore: score);
    }).toList()
      ..sort((a, b) => b.compatibilityScore.compareTo(a.compatibilityScore));
  }

  // ── Compatibility scoring algorithm ────────────────────────────────────
  double _calculateCompatibility(MatchableParent parent, List<String> userStages) {
    double score = 0.0;
    final userChildren = _onboarding.children;
    final userGroups = _groupService.getAllDefaultGroups().map((g) => g.id).toList();

    // 1. Same borough = base match (30%)
    final userBorough = _getUserBorough();
    if (parent.borough == userBorough) score += 0.30;

    // 2. Similar child ages (25%)
    if (userChildren.isNotEmpty && parent.childAges.isNotEmpty) {
      for (final childMap in userChildren) {
        final birthday = childMap['birthday'];
        if (birthday != null) {
          final childAge = _parseChildAgeMonths(birthday);
          for (final parentChildAge in parent.childAges) {
            final parentAge = _parseAgeStringToMonths(parentChildAge);
            final ageDiff = (childAge - parentAge).abs();
            if (ageDiff <= 3) {
              score += 0.25;
              break;
            } else if (ageDiff <= 6) {
              score += 0.18;
              break;
            } else if (ageDiff <= 12) {
              score += 0.10;
              break;
            }
          }
        }
      }
    } else if (userStages.isNotEmpty && parent.stagesOfLife.isNotEmpty) {
      // Match on life stage if no children data
      final overlap = userStages.where((s) => parent.stagesOfLife.contains(s)).length;
      score += (overlap / max(1, userStages.length)) * 0.25;
    }

    // 3. Shared groups (25%)
    if (userGroups.isNotEmpty && parent.groupIds.isNotEmpty) {
      final sharedGroups = userGroups.where((g) => parent.groupIds.contains(g)).length;
      score += (sharedGroups / max(1, parent.groupIds.length)) * 0.25;
    }

    // 4. Common meetup attendance (20%)
    final goingMeetups = _meetupService.meetups.where((m) => m.isGoing).toList();
    if (goingMeetups.isNotEmpty) {
      final sharedMeetups = goingMeetups.where(
        (m) => m.attendeeNames.any((name) => parent.name.startsWith(name.split(' ').first)),
      ).length;
      score += (sharedMeetups / max(1, goingMeetups.length)) * 0.20;
    } else {
      // Bonus for similar interests
      score += 0.08;
    }

    return score.clamp(0.0, 1.0);
  }

  // ── Suggestion generation ──────────────────────────────────────────────
  void _generateSuggestions() {
    final now = DateTime.now();
    final borough = _getUserBorough();
    final userStages = _onboarding.stagesOfLife;
    final userChildren = _onboarding.children;
    final topMatches = _nearbyParents.take(6).toList();
    final rng = Random(now.day + now.month);

    _suggestions = [];

    // Weather simulation based on month
    final isWinterish = now.month >= 11 || now.month <= 2;
    final isRainy = rng.nextDouble() > 0.6;
    final weatherNote = isRainy
        ? 'Rain expected tomorrow \u2014 indoor venue recommended'
        : isWinterish
            ? 'Chilly but dry \u2014 wrap up warm!'
            : 'Lovely weather forecast \u2014 perfect for outdoors!';

    // Suggestion 1: Child-age matched playdate
    if (userChildren.isNotEmpty || userStages.contains('parent')) {
      final playMatches = topMatches.where((p) => p.interests.any(
        (i) => i.toLowerCase().contains('play') || i.toLowerCase().contains('park'),
      )).take(4).toList();

      if (playMatches.isNotEmpty) {
        final sugDate = _nextWeekday(now, DateTime.saturday);
        _suggestions.add(SuggestedMeetup(
          id: 'sug_1',
          title: isRainy ? 'Soft Play Session' : 'Playdate at the Park',
          description: isRainy
              ? '${playMatches.length} parents with similar-aged kids are free this weekend. Soft play is perfect for a rainy day!'
              : '${playMatches.length} parents with similar-aged kids nearby. The forecast looks great for an outdoor playdate!',
          category: 'Playdate',
          suggestedLocation: isRainy
              ? 'Tumble Town Soft Play, $borough'
              : 'Cherry Hinton Hall, $borough',
          suggestedDate: _formatDate(sugDate),
          suggestedTime: '10:00 \u2013 11:30 AM',
          suggestedDateTime: DateTime(sugDate.year, sugDate.month, sugDate.day, 10, 0),
          matchedParents: playMatches,
          confidenceScore: 0.92,
          reasoning: 'Based on your children\'s ages and ${playMatches.length} nearby parents with kids in the same age range',
          weatherNote: weatherNote,
          iconEmoji: '\u{1F3DD}',
        ));
      }
    }

    // Suggestion 2: Coffee morning for new parents
    final coffeeMatches = topMatches.where((p) =>
      p.interests.any((i) => i.toLowerCase().contains('coffee')) ||
      p.childAges.any((a) => _parseAgeStringToMonths(a) <= 12),
    ).take(5).toList();

    if (coffeeMatches.isNotEmpty) {
      final sugDate = _nextWeekday(now, DateTime.wednesday);
      _suggestions.add(SuggestedMeetup(
        id: 'sug_2',
        title: 'Coffee & Chat \u2014 New Parents',
        description: '${coffeeMatches.length} parents near you also love coffee mornings. Meet other new parents in a relaxed setting.',
        category: 'Coffee',
        suggestedLocation: 'Little Bean Cafe, $borough',
        suggestedDate: _formatDate(sugDate),
        suggestedTime: '9:30 \u2013 11:00 AM',
        suggestedDateTime: DateTime(sugDate.year, sugDate.month, sugDate.day, 9, 30),
        matchedParents: coffeeMatches,
        confidenceScore: 0.88,
        reasoning: '${coffeeMatches.length} parents within walking distance are interested in coffee meetups and have babies under 12 months',
        iconEmoji: '\u2615',
      ));
    }

    // Suggestion 3: Active / outdoors meetup
    final walkMatches = topMatches.where((p) =>
      p.interests.any((i) =>
        i.toLowerCase().contains('walk') ||
        i.toLowerCase().contains('nature') ||
        i.toLowerCase().contains('cycling')),
    ).take(4).toList();

    if (walkMatches.isNotEmpty) {
      final sugDate = _nextWeekday(now, DateTime.friday);
      _suggestions.add(SuggestedMeetup(
        id: 'sug_3',
        title: isWinterish ? 'Winter Pram Walk' : 'Pram Walk & Picnic',
        description: isWinterish
            ? 'Brave the cold! ${walkMatches.length} active parents want to get out for a walk and hot chocolate after.'
            : '${walkMatches.length} parents nearby enjoy outdoor walks. Bring a picnic blanket and meet by the main gate!',
        category: 'Walk',
        suggestedLocation: 'Jesus Green, $borough',
        suggestedDate: _formatDate(sugDate),
        suggestedTime: '10:00 AM \u2013 12:00 PM',
        suggestedDateTime: DateTime(sugDate.year, sugDate.month, sugDate.day, 10, 0),
        matchedParents: walkMatches,
        confidenceScore: 0.85,
        reasoning: 'Matched ${walkMatches.length} parents who enjoy outdoor activities in your area',
        weatherNote: weatherNote,
        iconEmoji: '\u{1F6B6}',
      ));
    }

    // Suggestion 4: Dads-only meetup (if user is dad)
    if (_onboarding.parentType == 'dad') {
      final dadMatches = topMatches.where((p) =>
        p.groupIds.any((g) => g.contains('dad')),
      ).take(4).toList();

      if (dadMatches.isNotEmpty) {
        final sugDate = _nextWeekday(now, DateTime.sunday);
        _suggestions.add(SuggestedMeetup(
          id: 'sug_4',
          title: 'Dad\'s Sunday Brunch',
          description: 'Connect with ${dadMatches.length} local dads over brunch. Kids welcome \u2014 the restaurant has a play area!',
          category: 'Social',
          suggestedLocation: 'The Ivy Cafe, $borough',
          suggestedDate: _formatDate(sugDate),
          suggestedTime: '10:00 \u2013 12:00 PM',
          suggestedDateTime: DateTime(sugDate.year, sugDate.month, sugDate.day, 10, 0),
          matchedParents: dadMatches,
          confidenceScore: 0.90,
          reasoning: 'You\'re a dad \u2014 these ${dadMatches.length} dads are in your groups and live nearby',
          iconEmoji: '\u{1F468}\u200D\u{1F467}',
        ));
      }
    }

    // Suggestion 5: Expecting parents meetup
    if (userStages.contains('expecting')) {
      final expectingMatches = topMatches.where((p) =>
        p.stagesOfLife.contains('expecting'),
      ).take(3).toList();

      if (expectingMatches.isNotEmpty) {
        final sugDate = _nextWeekday(now, DateTime.thursday);
        _suggestions.add(SuggestedMeetup(
          id: 'sug_5',
          title: 'Expecting Parents Tea',
          description: '${expectingMatches.length} parents-to-be near you. Share tips, ask questions, and make friends before baby arrives!',
          category: 'Social',
          suggestedLocation: 'Community Centre, $borough',
          suggestedDate: _formatDate(sugDate),
          suggestedTime: '2:00 \u2013 3:30 PM',
          suggestedDateTime: DateTime(sugDate.year, sugDate.month, sugDate.day, 14, 0),
          matchedParents: expectingMatches,
          confidenceScore: 0.93,
          reasoning: 'You\'re expecting \u2014 meet ${expectingMatches.length} other parents-to-be in your borough',
          iconEmoji: '\u{1F930}',
        ));
      }
    }

    // Always add a general social suggestion
    final sugDate = _nextWeekday(now, DateTime.saturday, weeksAhead: 1);
    _suggestions.add(SuggestedMeetup(
      id: 'sug_general',
      title: 'Friday Night Dinner \u2014 Parents Only!',
      description: 'Leave the kids with a babysitter and enjoy an adults-only evening. ${topMatches.length} parents nearby are up for it!',
      category: 'Social',
      suggestedLocation: 'Trattoria Roma, Mill Road, $borough',
      suggestedDate: _formatDate(sugDate),
      suggestedTime: '7:00 \u2013 10:00 PM',
      suggestedDateTime: DateTime(sugDate.year, sugDate.month, sugDate.day, 19, 0),
      matchedParents: topMatches.take(4).toList(),
      confidenceScore: 0.80,
      reasoning: 'Everyone needs a night out! ${topMatches.length} active parents in your community',
      iconEmoji: '\u{1F37D}',
    ));

    // Sort by confidence
    _suggestions.sort((a, b) => b.confidenceScore.compareTo(a.confidenceScore));
  }

  /// Convert a suggestion into a real Meetup and add it to MeetupService
  Meetup createMeetupFromSuggestion(SuggestedMeetup suggestion) {
    final meetup = Meetup(
      id: 'mu_ai_${DateTime.now().millisecondsSinceEpoch}',
      title: suggestion.title,
      description: suggestion.description,
      category: suggestion.category,
      dateDisplay: suggestion.suggestedDate,
      timeDisplay: suggestion.suggestedTime,
      dateTime: suggestion.suggestedDateTime,
      location: suggestion.suggestedLocation,
      organiserName: _onboarding.name ?? 'You',
      organiserId: 'current_user',
      attendeeCount: 1,
      isGoing: true,
      attendeeNames: [_onboarding.name ?? 'You'],
      isFree: true,
      borough: _getUserBorough(),
      privacy: MeetupPrivacy.public,
      invitees: suggestion.matchedParents.map((p) => MeetupAttendee(
        id: p.id,
        name: p.name,
        avatarUrl: p.avatarUrl,
        status: 'invited',
      )).toList(),
    );

    _meetupService.createMeetup(meetup);
    return meetup;
  }

  // ── Helpers ────────────────────────────────────────────────────────────
  String _getUserBorough() {
    final pc = _onboarding.postcode;
    if (pc != null) return _postcode.getBoroughFromPostcode(pc) ?? 'Cambridge';
    return 'Cambridge';
  }

  int _parseChildAgeMonths(String birthday) {
    try {
      final parts = birthday.split('/');
      if (parts.length >= 2) {
        final month = int.parse(parts[0]);
        final year = int.parse(parts.last);
        final now = DateTime.now();
        final birth = DateTime(year, month);
        return ((now.difference(birth).inDays) / 30.44).round();
      }
    } catch (_) {}
    return 24; // default
  }

  int _parseAgeStringToMonths(String ageStr) {
    final lower = ageStr.toLowerCase();
    final numMatch = RegExp(r'(\d+)').firstMatch(lower);
    if (numMatch == null) return 24;
    final num = int.parse(numMatch.group(1)!);
    if (lower.contains('year')) return num * 12;
    return num; // months
  }

  DateTime _nextWeekday(DateTime from, int weekday, {int weeksAhead = 0}) {
    var d = from.add(Duration(days: 1 + weeksAhead * 7));
    while (d.weekday != weekday) {
      d = d.add(const Duration(days: 1));
    }
    return d;
  }

  String _formatDate(DateTime d) {
    const dayAbbr = ['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN'];
    const monthAbbr = ['JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC'];
    return '${dayAbbr[d.weekday - 1]}, ${monthAbbr[d.month - 1]} ${d.day}';
  }


}
