import 'dart:async';
import 'dart:convert';
import 'browser_storage.dart';

// =============================================================================
// MESSAGES AI SERVICE
//
// Powers the "Invisible AI" strategy for the Messages Tab:
//   - Predictive NLP search with auto-suggestions
//   - Adaptive interface reordering based on usage patterns
//   - Personalized quick-action recommendations
//   - AI-driven conversation prioritisation
//   - Feedback loops (like/dislike for learning)
//   - Voice command intent parsing
//   - Conversation health scoring
// =============================================================================

/// Predictive search suggestion derived from user context & history.
class AiSearchSuggestion {
  final String query;
  final String reason;
  final String icon;
  final double relevance;

  const AiSearchSuggestion({
    required this.query,
    required this.reason,
    required this.icon,
    this.relevance = 0.5,
  });
}

/// AI-generated quick action the user is likely to want.
class AiQuickAction {
  final String id;
  final String label;
  final String description;
  final String iconName;
  final String targetRoute;
  final Map<String, dynamic> routeArgs;
  final double confidence;

  const AiQuickAction({
    required this.id,
    required this.label,
    required this.description,
    required this.iconName,
    required this.targetRoute,
    this.routeArgs = const {},
    this.confidence = 0.5,
  });
}

/// Conversation insight generated by AI analysis.
class ConversationInsight {
  final String conversationId;
  final String insightText;
  final String category; // 'reply_needed', 'trending', 'quiet', 'action_item'
  final double urgency; // 0-1

  const ConversationInsight({
    required this.conversationId,
    required this.insightText,
    required this.category,
    this.urgency = 0.5,
  });
}

/// User feedback on an AI suggestion.
class AiMessageFeedback {
  final String suggestionId;
  final bool isPositive;
  final DateTime timestamp;
  final String? context;

  AiMessageFeedback({
    required this.suggestionId,
    required this.isPositive,
    DateTime? timestamp,
    this.context,
  }) : timestamp = timestamp ?? DateTime.now();

  Map<String, dynamic> toJson() => {
    'suggestionId': suggestionId,
    'isPositive': isPositive,
    'timestamp': timestamp.toIso8601String(),
    'context': context,
  };

  factory AiMessageFeedback.fromJson(Map<String, dynamic> json) =>
      AiMessageFeedback(
        suggestionId: json['suggestionId'] as String,
        isPositive: json['isPositive'] as bool,
        timestamp: DateTime.parse(json['timestamp'] as String),
        context: json['context'] as String?,
      );
}

/// Voice command intent parsed from natural language.
class VoiceIntent {
  final String action; // 'search', 'navigate', 'compose', 'pin', 'mute', 'archive'
  final String? target; // conversation name or ID
  final String? message; // for compose
  final double confidence;

  const VoiceIntent({
    required this.action,
    this.target,
    this.message,
    this.confidence = 0.8,
  });
}

/// Tracks how the user interacts with conversations for adaptive reordering.
class _UsageBehaviour {
  _UsageBehaviour();

  Map<String, int> conversationTaps = {};
  Map<String, int> searchQueries = {};
  Map<String, DateTime> lastInteraction = {};
  Set<String> frequentContacts = {};
  int totalSearches = 0;
  int totalTaps = 0;
  DateTime? lastActiveTime;

  /// Get conversations sorted by interaction frequency.
  List<String> get topConversations {
    final sorted = conversationTaps.entries.toList()
      ..sort((a, b) => b.value.compareTo(a.value));
    return sorted.take(5).map((e) => e.key).toList();
  }

  /// Get suggested search queries based on past searches.
  List<String> get topSearches {
    final sorted = searchQueries.entries.toList()
      ..sort((a, b) => b.value.compareTo(a.value));
    return sorted.take(5).map((e) => e.key).toList();
  }

  Map<String, dynamic> toJson() => {
    'conversationTaps': conversationTaps,
    'searchQueries': searchQueries,
    'lastInteraction': lastInteraction.map((k, v) => MapEntry(k, v.toIso8601String())),
    'frequentContacts': frequentContacts.toList(),
    'totalSearches': totalSearches,
    'totalTaps': totalTaps,
    'lastActiveTime': lastActiveTime?.toIso8601String(),
  };

  factory _UsageBehaviour.fromJson(Map<String, dynamic> json) {
    final b = _UsageBehaviour();
    b.conversationTaps = Map<String, int>.from(json['conversationTaps'] ?? {});
    b.searchQueries = Map<String, int>.from(json['searchQueries'] ?? {});
    final li = json['lastInteraction'] as Map<String, dynamic>? ?? {};
    b.lastInteraction = li.map((k, v) => MapEntry(k, DateTime.parse(v as String)));
    b.frequentContacts = Set<String>.from(json['frequentContacts'] ?? []);
    b.totalSearches = json['totalSearches'] as int? ?? 0;
    b.totalTaps = json['totalTaps'] as int? ?? 0;
    final lat = json['lastActiveTime'] as String?;
    b.lastActiveTime = lat != null ? DateTime.parse(lat) : null;
    return b;
  }
}

class MessagesAiService {
  static final MessagesAiService _instance = MessagesAiService._internal();
  factory MessagesAiService() => _instance;
  MessagesAiService._internal();

  static const String _behaviourKey = 'huddl_msg_ai_behaviour';
  static const String _feedbackKey = 'huddl_msg_ai_feedback';

  _UsageBehaviour _behaviour = _UsageBehaviour();
  final List<AiMessageFeedback> _feedbackHistory = [];
  bool _initialized = false;

  /// Current AI-generated insights for the message list.
  final List<ConversationInsight> _insights = [];
  List<ConversationInsight> get insights => List.unmodifiable(_insights);

  /// Whether the AI assistant overlay is visible.
  bool _assistantVisible = false;
  bool get isAssistantVisible => _assistantVisible;
  set assistantVisible(bool v) => _assistantVisible = v;

  Future<void> initialize() async {
    if (_initialized) return;
    try {
      final raw = await BrowserStorage.getString(_behaviourKey);
      if (raw != null && raw.isNotEmpty) {
        _behaviour = _UsageBehaviour.fromJson(json.decode(raw));
      }
      final fbRaw = await BrowserStorage.getString(_feedbackKey);
      if (fbRaw != null && fbRaw.isNotEmpty) {
        final List<dynamic> decoded = json.decode(fbRaw);
        _feedbackHistory.addAll(
          decoded.map((j) => AiMessageFeedback.fromJson(j as Map<String, dynamic>)),
        );
      }
    } catch (_) {
      // Start fresh on decode errors
    }
    _initialized = true;
  }

  Future<void> _persist() async {
    await BrowserStorage.setString(_behaviourKey, json.encode(_behaviour.toJson()));
    await BrowserStorage.setString(
      _feedbackKey,
      json.encode(_feedbackHistory.map((f) => f.toJson()).toList()),
    );
  }

  // ── Usage Tracking ──────────────────────────────────────────────────────

  /// Record a conversation tap for adaptive reordering.
  void recordConversationTap(String conversationId) {
    _behaviour.conversationTaps[conversationId] =
        (_behaviour.conversationTaps[conversationId] ?? 0) + 1;
    _behaviour.lastInteraction[conversationId] = DateTime.now();
    _behaviour.totalTaps++;
    _behaviour.lastActiveTime = DateTime.now();
    _persist();
  }

  /// Record a search query for predictive suggestions.
  void recordSearch(String query) {
    if (query.length < 2) return;
    final normalised = query.toLowerCase().trim();
    _behaviour.searchQueries[normalised] =
        (_behaviour.searchQueries[normalised] ?? 0) + 1;
    _behaviour.totalSearches++;
    _persist();
  }

  // ── Predictive Search ───────────────────────────────────────────────────

  /// Generate predictive search suggestions based on context.
  List<AiSearchSuggestion> getPredictiveSuggestions({
    String? partialQuery,
    List<String> recentGroupNames = const [],
    List<String> recentDMNames = const [],
  }) {
    final suggestions = <AiSearchSuggestion>[];

    // 1. Past searches (highest weight)
    for (final q in _behaviour.topSearches) {
      if (partialQuery == null || partialQuery.isEmpty || q.contains(partialQuery.toLowerCase())) {
        suggestions.add(AiSearchSuggestion(
          query: q,
          reason: 'Recent search',
          icon: '\u{1F50D}',
          relevance: 0.9,
        ));
      }
    }

    // 2. Frequent contacts
    for (final name in recentDMNames.take(3)) {
      if (partialQuery == null || partialQuery.isEmpty || name.toLowerCase().contains(partialQuery.toLowerCase())) {
        suggestions.add(AiSearchSuggestion(
          query: name,
          reason: 'Frequent contact',
          icon: '\u{1F464}',
          relevance: 0.8,
        ));
      }
    }

    // 3. Active groups
    for (final name in recentGroupNames.take(3)) {
      if (partialQuery == null || partialQuery.isEmpty || name.toLowerCase().contains(partialQuery.toLowerCase())) {
        suggestions.add(AiSearchSuggestion(
          query: name,
          reason: 'Active group',
          icon: '\u{1F465}',
          relevance: 0.7,
        ));
      }
    }

    // 4. Contextual suggestions based on time of day
    final hour = DateTime.now().hour;
    if (hour >= 6 && hour < 10) {
      suggestions.add(const AiSearchSuggestion(
        query: 'morning meetup',
        reason: 'Good morning! Looking for today\'s plans?',
        icon: '\u2600\uFE0F',
        relevance: 0.6,
      ));
    } else if (hour >= 17 && hour < 21) {
      suggestions.add(const AiSearchSuggestion(
        query: 'weekend activities',
        reason: 'Evening! Planning weekend activities?',
        icon: '\u{1F31F}',
        relevance: 0.6,
      ));
    }

    // Sort by relevance and deduplicate
    final seen = <String>{};
    suggestions.retainWhere((s) => seen.add(s.query.toLowerCase()));
    suggestions.sort((a, b) => b.relevance.compareTo(a.relevance));
    return suggestions.take(5).toList();
  }

  // ── Adaptive Interface ──────────────────────────────────────────────────

  /// Get the adaptive priority score for a conversation.
  /// Higher score = shown higher in the list.
  double getConversationPriority(String conversationId, {
    bool isPinned = false,
    int unreadCount = 0,
    DateTime? lastMessageTime,
  }) {
    double score = 0;

    // Pinned always on top
    if (isPinned) score += 1000;

    // Unread messages boost
    score += unreadCount * 50;

    // Recency boost (decay over time)
    if (lastMessageTime != null) {
      final minutesAgo = DateTime.now().difference(lastMessageTime).inMinutes;
      score += (1000 / (1 + minutesAgo * 0.1));
    }

    // Usage frequency boost
    final taps = _behaviour.conversationTaps[conversationId] ?? 0;
    score += taps * 10;

    // Recent interaction boost
    final lastInteraction = _behaviour.lastInteraction[conversationId];
    if (lastInteraction != null) {
      final hoursAgo = DateTime.now().difference(lastInteraction).inHours;
      if (hoursAgo < 24) score += 30;
      if (hoursAgo < 1) score += 50;
    }

    return score;
  }

  /// Determine which features should be hidden (rarely used).
  Set<String> getHiddenFeatures() {
    final hidden = <String>{};

    // If user has never searched, hide the search prominently
    if (_behaviour.totalSearches < 3) {
      hidden.add('prominent_search');
    }

    // If user rarely uses archive, de-emphasize it
    // (tracked implicitly through low tap count on archive actions)

    return hidden;
  }

  // ── Quick Actions ───────────────────────────────────────────────────────

  /// Generate contextual quick actions based on user behaviour.
  List<AiQuickAction> getQuickActions({
    int totalUnread = 0,
    bool hasPendingInvitations = false,
    List<String> recentGroupIds = const [],
  }) {
    final actions = <AiQuickAction>[];

    // Unread catch-up
    if (totalUnread > 5) {
      actions.add(AiQuickAction(
        id: 'catch_up',
        label: 'Catch up',
        description: '$totalUnread unread messages across your chats',
        iconName: 'auto_awesome',
        targetRoute: '/ai_catch_up',
        confidence: 0.9,
      ));
    }

    // Pending invitations
    if (hasPendingInvitations) {
      actions.add(const AiQuickAction(
        id: 'invitations',
        label: 'View invites',
        description: 'You have pending group invitations',
        iconName: 'mail',
        targetRoute: '/invitations',
        confidence: 0.85,
      ));
    }

    // Most-used conversation shortcut
    final topConvs = _behaviour.topConversations;
    if (topConvs.isNotEmpty) {
      actions.add(AiQuickAction(
        id: 'frequent_chat',
        label: 'Open frequent chat',
        description: 'Jump to your most-visited conversation',
        iconName: 'chat',
        targetRoute: '/chat',
        routeArgs: {'conversationId': topConvs.first},
        confidence: 0.7,
      ));
    }

    actions.sort((a, b) => b.confidence.compareTo(a.confidence));
    return actions.take(3).toList();
  }

  // ── Conversation Insights ───────────────────────────────────────────────

  /// Generate contextual insights for conversations.
  void generateInsights({
    required List<Map<String, dynamic>> conversations,
  }) {
    _insights.clear();

    for (final conv in conversations) {
      final id = conv['id'] as String? ?? '';
      final unread = conv['unreadCount'] as int? ?? 0;
      final lastTime = conv['lastMessageTime'] as DateTime?;
      final name = conv['name'] as String? ?? '';

      // Reply needed insight
      if (unread > 3) {
        _insights.add(ConversationInsight(
          conversationId: id,
          insightText: '$name has $unread messages waiting',
          category: 'reply_needed',
          urgency: (unread / 10).clamp(0.3, 1.0),
        ));
      }

      // Quiet conversation insight
      if (lastTime != null && DateTime.now().difference(lastTime).inDays > 7) {
        _insights.add(ConversationInsight(
          conversationId: id,
          insightText: 'No activity in $name for a week',
          category: 'quiet',
          urgency: 0.3,
        ));
      }
    }
  }

  /// Get insight for a specific conversation.
  ConversationInsight? getInsightFor(String conversationId) {
    try {
      return _insights.firstWhere((i) => i.conversationId == conversationId);
    } catch (_) {
      return null;
    }
  }

  // ── Voice Command Parsing ───────────────────────────────────────────────

  /// Parse a voice command into an actionable intent.
  VoiceIntent parseVoiceCommand(String command) {
    final lower = command.toLowerCase().trim();

    // Search intent
    if (lower.startsWith('search') || lower.startsWith('find') || lower.startsWith('look for')) {
      final query = lower
          .replaceFirst(RegExp(r'^(search|find|look for)\s+(for\s+)?'), '')
          .trim();
      return VoiceIntent(action: 'search', target: query, confidence: 0.9);
    }

    // Navigate intent
    if (lower.startsWith('open') || lower.startsWith('go to') || lower.startsWith('show')) {
      final target = lower
          .replaceFirst(RegExp(r'^(open|go to|show)\s+'), '')
          .trim();
      return VoiceIntent(action: 'navigate', target: target, confidence: 0.85);
    }

    // Compose intent
    if (lower.startsWith('message') || lower.startsWith('send') || lower.startsWith('tell')) {
      final parts = lower
          .replaceFirst(RegExp(r'^(message|send|tell)\s+'), '')
          .split(RegExp(r'\s+that\s+|\s+saying\s+'));
      return VoiceIntent(
        action: 'compose',
        target: parts.isNotEmpty ? parts[0].trim() : null,
        message: parts.length > 1 ? parts[1].trim() : null,
        confidence: 0.8,
      );
    }

    // Pin/Mute intent
    if (lower.contains('pin')) {
      final target = lower.replaceAll(RegExp(r'(un)?pin\s*'), '').trim();
      return VoiceIntent(action: 'pin', target: target, confidence: 0.85);
    }
    if (lower.contains('mute')) {
      final target = lower.replaceAll(RegExp(r'(un)?mute\s*'), '').trim();
      return VoiceIntent(action: 'mute', target: target, confidence: 0.85);
    }

    // Archive intent
    if (lower.contains('archive')) {
      final target = lower.replaceAll('archive', '').trim();
      return VoiceIntent(action: 'archive', target: target, confidence: 0.8);
    }

    // Catch-up intent
    if (lower.contains('catch up') || lower.contains('summarise') || lower.contains('summarize')) {
      return const VoiceIntent(action: 'catch_up', confidence: 0.9);
    }

    // Default: treat as search
    return VoiceIntent(action: 'search', target: lower, confidence: 0.5);
  }

  // ── Feedback Loop ───────────────────────────────────────────────────────

  /// Record user feedback on an AI suggestion.
  void recordFeedback(AiMessageFeedback feedback) {
    _feedbackHistory.add(feedback);
    // Keep last 100 feedback items
    if (_feedbackHistory.length > 100) {
      _feedbackHistory.removeRange(0, _feedbackHistory.length - 100);
    }
    _persist();
  }

  /// Get the ratio of positive feedback (for AI confidence display).
  double get feedbackSatisfactionRate {
    if (_feedbackHistory.isEmpty) return 0.8; // default assumption
    final positive = _feedbackHistory.where((f) => f.isPositive).length;
    return positive / _feedbackHistory.length;
  }

  // ── Smart Reply Suggestions ─────────────────────────────────────────────

  /// Generate quick reply suggestions based on the last message.
  List<String> getSmartReplies(String lastMessage) {
    final lower = lastMessage.toLowerCase();

    if (lower.contains('?') || lower.contains('what') || lower.contains('when') || lower.contains('where')) {
      if (lower.contains('meet') || lower.contains('plan')) {
        return ['Sounds great!', 'I\'m free this weekend', 'Let me check my calendar'];
      }
      if (lower.contains('tried') || lower.contains('recommend')) {
        return ['Yes, loved it!', 'Not yet, tell me more', 'I\'ll check it out'];
      }
      return ['Let me think about it', 'Good question!', 'I\'ll get back to you'];
    }

    if (lower.contains('thank') || lower.contains('thanks')) {
      return ['You\'re welcome!', 'Happy to help!', 'Anytime!'];
    }

    if (lower.contains('hello') || lower.contains('hi ') || lower.startsWith('hi')) {
      return ['Hey! How are you?', 'Hi there!', 'Hello!'];
    }

    // Default contextual replies
    return ['Sounds good!', 'Thanks for sharing', 'Got it!'];
  }
}
