#!/usr/bin/env python3
"""
replace_icons.py — Step 3 of the Huddl icon system overhaul.

Replaces all Icons.xxx / CupertinoIcons.xxx references across lib/ dart files
with the corresponding HuddlIcons constant from lib/theme/huddl_icons.dart.

Rules:
  • Icons.xxx                → HuddlIcons.xxx  (using mapping table)
  • CupertinoIcons.xxx       → HuddlIcons.xxx  (using mapping table)
  • Active/Fill states        → PhosphorIconsFill.xxx (kept as-is from HuddlIcons)
  • No-equivalent entries     → PhosphorIconsRegular.question (flagged in report)
  • Unknown entries           → LEFT UNCHANGED, logged to report for manual review
  • Imports of material/cupertino packages stay (may still be needed for other deps)
"""

import re
import os
import sys
from pathlib import Path

# ── MAPPING TABLE ────────────────────────────────────────────────────────────
# Icons.xxx  →  HuddlIcons.xxx
# Sorted longest-first to prevent prefix conflicts (e.g. arrow_back_ios_new before arrow_back_ios)

ICONS_MAP = {
    # Navigation — back
    "arrow_back_ios_new_rounded": "arrowBack",
    "arrow_back_ios_new":         "arrowBack",
    "arrow_back_ios_rounded":     "arrowBack",
    "arrow_back_ios":             "arrowBack",
    "arrow_back_rounded":         "arrowBack",
    "arrow_back":                 "arrowBack",
    # Navigation — forward
    "arrow_forward_ios_rounded":  "arrowForward",
    "arrow_forward_ios":          "arrowForward",
    "arrow_forward_rounded":      "arrowForward",
    "arrow_forward":              "arrowForward",
    # Navigation — arrows
    "arrow_upward_rounded":       "arrowUp",
    "arrow_upward":               "arrowUp",
    "arrow_downward_rounded":     "arrowDown",
    "arrow_downward":             "arrowDown",
    "arrow_drop_up":              "caretUp",
    "arrow_drop_down":            "caretDown",
    # Chevrons / carets
    "chevron_left_rounded":       "caretLeft",
    "chevron_left":               "caretLeft",
    "chevron_right_rounded":      "caretRight",
    "chevron_right":              "caretRight",
    "keyboard_arrow_left_rounded": "caretLeft",
    "keyboard_arrow_left":        "caretLeft",
    "keyboard_arrow_right_rounded": "caretRight",
    "keyboard_arrow_right":       "caretRight",
    "keyboard_arrow_down_rounded": "caretDown",
    "keyboard_arrow_down":        "caretDown",
    "keyboard_arrow_up_rounded":  "caretUp",
    "keyboard_arrow_up":          "caretUp",
    "expand_more_rounded":        "caretDown",
    "expand_more":                "caretDown",
    "expand_less_rounded":        "caretUp",
    "expand_less":                "caretUp",
    # Person / user
    "person_add_alt_1_rounded":   "personAdd",
    "person_add_alt_rounded":     "personAdd",
    "person_add_rounded":         "personAdd",
    "person_add_alt_1":           "personAdd",
    "person_add_alt":             "personAdd",
    "person_add":                 "personAdd",
    "person_remove_alt_1_rounded": "personRemove",
    "person_remove_rounded":      "personRemove",
    "person_remove":              "personRemove",
    "person_search":              "personSearchIcon",
    "person_outline_rounded":     "user",
    "person_outline":             "user",
    "person_rounded":             "user",
    "person":                     "user",
    "face_2":                     "user",
    "face_3":                     "user",
    "face_retouching_natural_rounded": "faceRetouching",
    "face":                       "user",
    "manage_accounts":            "manageAccounts",
    "account_circle_outlined":    "user",
    "account_circle":             "userFill",
    "account_box_outlined":       "user",
    "account_box":                "userFill",
    # People / groups
    "people_alt_rounded":         "usersThree",
    "people_outline_rounded":     "usersThree",
    "people_outlined":            "usersThree",
    "people_outline":             "usersThree",
    "people_rounded":             "usersThree",
    "people":                     "usersThree",
    "group_add_rounded":          "userGroupPlus",
    "group_add":                  "userGroupPlus",
    "group_remove_rounded":       "userGroupMinus",
    "group_remove":               "userGroupMinus",
    "groups_outlined":            "usersThree",
    "groups_rounded":             "usersThree",
    "groups":                     "usersThree",
    "group_outlined":             "usersThree",
    "group_rounded":              "usersThree",
    "group":                      "usersThree",
    # Bookmark / save
    "bookmark_add_outlined":      "bookmarkPlus",
    "bookmark_add":               "bookmarkPlus",
    "bookmark_added_rounded":     "bookmarkFill",
    "bookmark_added":             "bookmarkFill",
    "bookmark_remove_outlined":   "bookmark",
    "bookmark_border_rounded":    "bookmark",
    "bookmark_border":            "bookmark",
    "bookmark_outline_rounded":   "bookmark",
    "bookmark_outline":           "bookmark",
    "bookmark_rounded":           "bookmarkFill",
    "bookmark":                   "bookmark",
    # Heart / favourite
    "favorite_border_rounded":    "heart",
    "favorite_border":            "heart",
    "favorite_outline_rounded":   "heart",
    "favorite_outline":           "heart",
    "favorite_rounded":           "heartFill",
    "favorite":                   "heartFill",
    # Star
    "star_border_rounded":        "star",
    "star_outline_rounded":       "star",
    "star_outline":               "star",
    "star_half_rounded":          "starHalf",
    "star_half":                  "starHalf",
    "star_rounded":               "starFill",
    "star":                       "star",
    "rate_review":                "rateReview",
    # Thumbs
    "thumb_up_alt_rounded":       "thumbUpFill",
    "thumb_up_rounded":           "thumbUpFill",
    "thumb_up_outlined":          "thumbUp",
    "thumb_up_alt":               "thumbUp",
    "thumb_up":                   "thumbUp",
    "thumb_down_alt_rounded":     "thumbDownFill",
    "thumb_down_rounded":         "thumbDownFill",
    "thumb_down_outlined":        "thumbDown",
    "thumb_down_alt":             "thumbDown",
    "thumb_down":                 "thumbDown",
    "thumbs_up_down":             "thumbsUpDown",
    # Chat / message
    "chat_bubble_outline_rounded": "chat",
    "chat_bubble_outline":        "chat",
    "chat_bubble_outlined":       "chat",
    "chat_bubble_rounded":        "chatFill",
    "chat_bubble":                "chatFill",
    "chat_outlined":              "chat",
    "chat_rounded":               "chatFill",
    "chat":                       "chat",
    "message_outlined":           "chat",
    "message_rounded":            "chatFill",
    "message":                    "chatFill",
    "comment_outlined":           "chat",
    "comment":                    "chatFill",
    "forum_outlined":             "forum",
    "forum":                      "forum",
    "question_answer_outlined":   "questionAnswer",
    "question_answer":            "questionAnswer",
    "feedback":                   "feedback",
    "sms_outlined":               "chat",
    "sms":                        "chatFill",
    # Send / reply
    "send_outlined":              "send",
    "send_rounded":               "send",
    "send":                       "send",
    "reply_rounded":              "reply",
    "reply":                      "reply",
    "forward_outlined":           "forward",
    "forward_to_inbox_outlined":  "forward",
    "forward":                    "forward",
    # Share
    "share_outlined":             "share",
    "share":                      "share",
    "ios_share":                  "share",
    # Copy
    "content_copy_rounded":       "copy",
    "content_copy":               "copy",
    "copy_all_rounded":           "copy",
    "copy_all":                   "copy",
    # Phone / contact
    "phone_outlined":             "phone",
    "phone_in_talk_outlined":     "phone",
    "phone_enabled_outlined":     "phone",
    "phone":                      "phone",
    "contacts":                   "contacts",
    "contact_phone_outlined":     "phone",
    "call_outlined":              "phone",
    "call":                       "phone",
    # Email
    "mark_email_unread_outlined": "email",
    "mail_outline":               "email",
    "email_outlined":             "email",
    "email":                      "email",
    # Notifications / bell
    "notifications_active_outlined": "bellRinging",
    "notifications_active":       "bellRingingFill",
    "notifications_none_rounded": "bell",
    "notifications_none":         "bell",
    "notifications_off_outlined": "bellSlash",
    "notifications_off_rounded":  "bellSlash",
    "notifications_off":          "bellSlash",
    "notifications_outlined":     "bell",
    "notifications_rounded":      "bellFill",
    "notifications_paused_outlined": "bellSlash",
    "notifications":              "bellFill",
    "notification_add_outlined":  "bellRinging",
    "notification_add":           "bellRingingFill",
    # Clock / time
    "access_time_outlined":       "clock",
    "access_time_rounded":        "clock",
    "access_time":                "clock",
    "schedule_outlined":          "clock",
    "schedule_send_outlined":     "clock",
    "schedule":                   "clock",
    "timer_outlined":             "alarm",
    "timer_rounded":              "alarm",
    "timer":                      "alarm",
    "alarm_rounded":              "alarm",
    "alarm":                      "alarm",
    "pending_actions":            "clockCountdown",
    "hourglass_empty":            "hourglass",
    "hourglass_bottom_rounded":   "hourglass",
    "hourglass_top_rounded":      "hourglass",
    # Calendar / event
    "event_available_outlined":   "calendarCheck",
    "event_available":            "calendarCheck",
    "event_busy_outlined":        "calendarX",
    "event_busy":                 "calendarX",
    "event_note_outlined":        "calendar",
    "event_note":                 "calendar",
    "event_outlined":             "calendar",
    "event_rounded":              "calendar",
    "event":                      "calendar",
    "calendar_today_outlined":    "calendar",
    "calendar_today":             "calendar",
    "calendar_month_outlined":    "calendar",
    "calendar_month":             "calendar",
    "upcoming_outlined":          "upcoming",
    "upcoming":                   "upcoming",
    "date_range_outlined":        "calendar",
    "date_range":                 "calendar",
    # Search
    "search_off_rounded":         "searchOff",
    "search_off":                 "searchOff",
    "search_rounded":             "search",
    "search":                     "search",
    "manage_search":              "search",
    # Home
    "home_outlined":              "home",
    "home_rounded":               "homeFill",
    "home":                       "home",
    # Map / location
    "location_on_outlined":       "locationPin",
    "location_on_rounded":        "locationPinFill",
    "location_on":                "locationPinFill",
    "location_off_rounded":       "locationOff",
    "location_off":               "locationOff",
    "place_outlined":             "locationPin",
    "place_rounded":              "locationPinFill",
    "place":                      "locationPinFill",
    "near_me_rounded":            "nearMe",
    "near_me_outlined":           "nearMe",
    "near_me":                    "nearMe",
    "map_outlined":               "map",
    "map":                        "map",
    "explore_outlined":           "exploreOutlined",
    "explore_rounded":            "explore",
    "explore":                    "explore",
    "directions_walk":            "walk",
    "directions_run":             "run",
    "directions_car":             "work",
    "my_location":                "nearMe",
    # Edit
    "edit_outlined":              "edit",
    "edit_note_rounded":          "note",
    "edit_note":                  "note",
    "edit_rounded":               "edit",
    "edit":                       "edit",
    "edit_location_alt_outlined": "editLocation",
    "edit_location":              "editLocation",
    "border_color":               "edit",
    "create_outlined":            "edit",
    "create":                     "edit",
    "draw_outlined":              "edit",
    "draw":                       "edit",
    # Text / content
    "title":                      "title",
    "description_outlined":       "description",
    "description_rounded":        "description",
    "description":                "description",
    "article_outlined":           "article",
    "article_rounded":            "article",
    "article":                    "article",
    "short_text":                 "shortText",
    "text_fields":                "title",
    "notes_outlined":             "note",
    "notes":                      "note",
    "text_snippet_outlined":      "note",
    "assignment_outlined":        "assignment",
    "assignment_rounded":         "assignment",
    "assignment_turned_in_outlined": "checkSquare",
    "assignment_turned_in":       "checkSquareFill",
    "assignment":                 "assignment",
    # Books / reading
    "auto_stories_outlined":      "books",
    "auto_stories":               "books",
    "menu_book_outlined":         "menuBook",
    "menu_book":                  "menuBook",
    "library_books_outlined":     "books",
    "library_books":              "books",
    "import_contacts_outlined":   "books",
    "import_contacts":            "books",
    # Camera / photo
    "camera_alt_outlined":        "camera",
    "camera_alt_rounded":         "camera",
    "camera_alt":                 "camera",
    "camera_outlined":            "camera",
    "camera":                     "camera",
    "add_a_photo_outlined":       "cameraPlus",
    "add_a_photo_rounded":        "cameraPlus",
    "add_a_photo":                "cameraPlus",
    "photo_camera_outlined":      "camera",
    "photo_camera":               "camera",
    # Photo / image / gallery
    "add_photo_alternate_outlined": "photoLibrary",
    "add_photo_alternate":        "photoLibrary",
    "photo_library_outlined":     "photoLibrary",
    "photo_library_rounded":      "photoLibrary",
    "photo_library":              "photoLibrary",
    "image_outlined":             "image",
    "image_rounded":              "image",
    "image_not_supported":        "imageNotSupported",
    "image":                      "image",
    "broken_image_rounded":       "brokenImage",
    "broken_image":               "brokenImage",
    "photo_outlined":             "image",
    "photo":                      "image",
    # Video
    "videocam_outlined":          "videocam",
    "videocam_off_outlined":      "videocam",
    "videocam":                   "videocam",
    "video_camera_back_outlined": "videocam",
    "ondemand_video_outlined":    "videocam",
    # Mic / audio
    "mic_none_rounded":           "mic",
    "mic_none":                   "mic",
    "mic_outlined":               "mic",
    "mic_off_outlined":           "micOff",
    "mic_off_rounded":            "micOff",
    "mic_off":                    "micOff",
    "mic_rounded":                "micFill",
    "mic":                        "mic",
    "record_voice_over_outlined": "voiceOver",
    "record_voice_over":          "voiceOver",
    "voice_over_off_outlined":    "micOff",
    "keyboard_voice_outlined":    "mic",
    # Play / media controls
    "play_circle_outline_rounded": "playCircle",
    "play_circle_outline":        "playCircle",
    "play_circle_outlined":       "playCircle",
    "play_circle_filled":         "playFill",
    "play_circle":                "playCircle",
    "play_arrow_rounded":         "play",
    "play_arrow_outlined":        "play",
    "play_arrow":                 "play",
    "pause_circle_outlined":      "pauseCircle",
    "pause_circle":               "pauseCircle",
    "pause_rounded":              "pause",
    "pause":                      "pause",
    "stop_circle_outlined":       "stopCircle",
    "stop_rounded":               "stop",
    "stop":                       "stop",
    "fiber_manual_record":        "record",
    "radio_button_unchecked":     "radioOff",
    "radio_button_checked":       "radioOnFill",
    "volume_up_rounded":          "mic",
    "volume_off_rounded":         "micOff",
    # Music
    "music_note_rounded":         "musicNote",
    "music_note":                 "musicNote",
    "audiotrack_rounded":         "musicNote",
    # File / document
    "attach_file_rounded":        "fileInsert",
    "attach_file":                "fileInsert",
    "attachment_rounded":         "fileInsert",
    "attachment":                 "fileInsert",
    "insert_drive_file_outlined": "file",
    "insert_drive_file":          "file",
    "file_upload_outlined":       "upload",
    "file_upload":                "upload",
    "file_download_outlined":     "download",
    "file_download":              "download",
    "download_rounded":           "download",
    "upload_rounded":             "upload",
    "cloud_upload_outlined":      "cloudUpload",
    "cloud_upload":               "cloudUpload",
    "cloud_download_outlined":    "download",
    "cloud_done_outlined":        "cloudDone",
    "cloud_done":                 "cloudDone",
    "cloud_off_outlined":         "cloudOff",
    "cloud_off":                  "cloudOff",
    "cloud_outlined":             "cloud",
    "cloud_sync":                 "cloudDone",
    "cloud":                      "cloud",
    "backup_outlined":            "backup",
    "backup":                     "backup",
    "storage":                    "storage",
    # Commerce
    "storefront_outlined":        "storefront",
    "storefront_rounded":         "storefrontFill",
    "storefront":                 "storefront",
    "store_outlined":             "storefront",
    "store_mall_directory_outlined": "storefront",
    "store":                      "storefront",
    "shopping_bag_outlined":      "shoppingBag",
    "shopping_bag":               "shoppingBag",
    "shopping_cart_outlined":     "shoppingBag",
    "shopping_cart":              "shoppingBag",
    "sell_outlined":              "sellTag",
    "sell_rounded":               "sellTagFill",
    "sell":                       "sellTag",
    "local_offer_outlined":       "localOffer",
    "local_offer_rounded":        "localOffer",
    "local_offer":                "localOffer",
    "credit_card_outlined":       "creditCard",
    "credit_card":                "creditCard",
    "payment":                    "payment",
    "attach_money":               "money",
    "money_off_csred":            "moneyOff",
    "money_off":                  "moneyOff",
    "account_balance_wallet_outlined": "payment",
    "account_balance_wallet":     "payment",
    "account_balance":            "bank",
    "price_check":                "sellTag",
    "receipt_long_outlined":      "receipt",
    "receipt_outlined":           "receipt",
    "receipt":                    "receipt",
    # Work / business
    "work_outline_rounded":       "work",
    "work_outline":               "work",
    "work_outlined":              "work",
    "work_off_outlined":          "work",
    "work":                       "work",
    "business_center":            "work",
    "business_outlined":          "business",
    "business":                   "business",
    "domain_outlined":            "business",
    "domain":                     "business",
    # Safety / lock / shield
    "lock_outline_rounded":       "lock",
    "lock_outline":               "lock",
    "lock_outlined":              "lock",
    "lock_open_outlined":         "lockOpen",
    "lock_open_rounded":          "lockOpen",
    "lock_open":                  "lockOpen",
    "lock_reset":                 "lockReset",
    "lock":                       "lockFill",
    "shield_outlined":            "shield",
    "shield":                     "shield",
    "security_rounded":           "shieldCheck",
    "security":                   "shieldCheck",
    "verified_user_outlined":     "verifiedUser",
    "verified_user":              "verifiedUserFill",
    "gpp_good_outlined":          "shieldCheck",
    "gpp_maybe_outlined":         "shield",
    "health_and_safety_outlined": "medical",
    "health_and_safety":          "medical",
    "fingerprint":                "fingerprint",
    "key_outlined":               "key",
    "key":                        "key",
    "no_encryption_outlined":     "lockOpen",
    "enhanced_encryption_outlined": "lock",
    # Verified / trust
    "verified_outlined":          "verified",
    "verified_rounded":           "verifiedFill",
    "verified":                   "verifiedFill",
    "new_releases_outlined":      "bellRinging",
    # Block / report
    "block_rounded":              "block",
    "block":                      "block",
    "person_off_rounded":         "personOff",
    "person_off":                 "personOff",
    "report_outlined":            "flag",
    "report_rounded":             "flag",
    "report_problem_outlined":    "warning",
    "report_problem":             "warning",
    "report_gmailerrorred_outlined": "flag",
    "report":                     "flag",
    "flag_outlined":              "flag",
    "flag_rounded":               "flagFill",
    "flag":                       "flag",
    # Info / status
    "info_outline_rounded":       "info",
    "info_outlined":              "info",
    "info_outline":               "info",
    "info_rounded":               "infoFill",
    "info":                       "infoFill",
    "help_outline_rounded":       "info",
    "help_outline":               "info",
    "help_outlined":              "info",
    "help_center_outlined":       "info",
    "help":                       "infoFill",
    "contact_support_outlined":   "info",
    # Warning / error
    "warning_amber_rounded":      "warning",
    "warning_amber":              "warning",
    "warning_rounded":            "warningFill",
    "warning":                    "warning",
    "error_outline_rounded":      "error",
    "error_outline":              "error",
    "error_outlined":             "error",
    "error_rounded":              "errorFill",
    "error":                      "errorFill",
    "dangerous_rounded":          "emergency",
    "dangerous_outlined":         "emergency",
    "priority_high":              "priority",
    # Check / done
    "done_all_rounded":           "check",
    "done_all":                   "check",
    "done_rounded":               "check",
    "done_outlined":              "check",
    "done":                       "check",
    "check_rounded":              "check",
    "check_outlined":             "check",
    "check":                      "check",
    "check_circle_outline_rounded": "checkCircle",
    "check_circle_outline":       "checkCircle",
    "check_circle_outlined":      "checkCircle",
    "check_circle_rounded":       "checkCircleFill",
    "check_circle":               "checkCircle",
    "check_box_outline_blank_rounded": "checkSquare",
    "check_box_outline_blank":    "checkSquare",
    "check_box_rounded":          "checkSquareFill",
    "check_box":                  "checkSquareFill",
    "checklist_rounded":          "checklist",
    "checklist":                  "checklist",
    "fact_check_outlined":        "factCheck",
    "fact_check":                 "factCheck",
    # Circle / shapes
    "circle_outlined":            "circle",
    "circle":                     "circleFill",
    "remove_circle_outline_rounded": "removeCircle",
    "remove_circle_outline":      "removeCircle",
    "remove_circle_outlined":     "removeCircle",
    "remove_circle":              "removeCircle",
    # Cancel / close
    "cancel_outlined":            "cancel",
    "cancel_rounded":             "cancel",
    "cancel":                     "cancel",
    "close_outlined":             "close",
    "close_rounded":              "close",
    "close":                      "close",
    "clear_rounded":              "close",
    "clear":                      "close",
    "highlight_off_rounded":      "close",
    "highlight_off":              "close",
    # Add / remove
    "add_rounded":                "add",
    "add_circle_outline_rounded": "addCircle",
    "add_circle_outline":         "addCircle",
    "add_circle_outlined":        "addCircle",
    "add_circle_rounded":         "addCircleFill",
    "add_circle":                 "addCircle",
    "add_business":               "addBusiness",
    "add":                        "add",
    "remove_rounded":             "remove",
    "remove":                     "remove",
    # More / menu
    "more_horiz_rounded":         "moreHoriz",
    "more_horiz":                 "moreHoriz",
    "more_vert_rounded":          "moreVert",
    "more_vert":                  "moreVert",
    "menu_rounded":               "menu",
    "menu":                       "menu",
    # Grid / list
    "grid_view_rounded":          "gridView",
    "grid_view":                  "gridView",
    "grid_on_rounded":            "gridView",
    "grid_on":                    "gridView",
    "view_list_rounded":          "viewList",
    "view_list":                  "viewList",
    "list_rounded":               "listView",
    "list_alt_rounded":           "listView",
    "list_alt":                   "listView",
    "list":                       "listView",
    # Filter / sort / tune
    "tune_rounded":               "filter",
    "tune":                       "filter",
    "filter_list_rounded":        "filter",
    "filter_list_off_rounded":    "filterOff",
    "filter_list":                "filter",
    "filter_alt_outlined":        "filterOff",
    "filter_alt_rounded":         "filterFill",
    "filter_alt":                 "filter",
    "sort_by_alpha_outlined":     "sortAscending",
    "sort_by_alpha":              "sortAscending",
    "sort_rounded":               "sortAscending",
    "sort":                       "sortAscending",
    "swap_vert_rounded":          "sortAscending",
    "swap_vert":                  "sortAscending",
    # Open / link
    "open_in_new_rounded":        "openInNew",
    "open_in_new_off_rounded":    "openInNew",
    "open_in_new":                "openInNew",
    "open_in_browser":            "openInBrowser",
    "link_rounded":               "link",
    "link_off_rounded":           "close",
    "link":                       "link",
    "launch":                     "openInNew",
    # Pin
    "push_pin_outlined":          "pin",
    "push_pin_rounded":           "pinFill",
    "push_pin":                   "pin",
    # Delete / trash
    "delete_forever_outlined":    "delete",
    "delete_forever_rounded":     "delete",
    "delete_forever":             "delete",
    "delete_sweep_outlined":      "delete",
    "delete_outline_rounded":     "delete",
    "delete_outline":             "delete",
    "delete_rounded":             "deleteFill",
    "delete":                     "delete",
    "archive_outlined":           "archive",
    "archive":                    "archive",
    # Refresh / reload
    "replay_outlined":            "replay",
    "replay_30":                  "replay",
    "replay":                     "replay",
    "refresh_rounded":            "refresh",
    "refresh":                    "refresh",
    "update_rounded":             "refresh",
    "update":                     "refresh",
    "restore_rounded":            "refresh",
    "restore":                    "refresh",
    "repeat_rounded":             "refresh",
    "repeat":                     "refresh",
    "sync_rounded":               "refresh",
    "sync_problem_rounded":       "refresh",
    "sync":                       "refresh",
    # Settings
    "settings_outlined":          "settings",
    "settings_rounded":           "settingsFill",
    "settings":                   "settings",
    "build_outlined":             "settings",
    "build_rounded":              "settings",
    "build_circle_outlined":      "settings",
    "handyman_outlined":          "settings",
    "construction_rounded":       "settings",
    # Language / globe
    "language_outlined":          "language",
    "language":                   "language",
    "public_rounded":             "language",
    "public_off_rounded":         "close",
    "public":                     "language",
    # Visibility
    "visibility_off_outlined":    "visibilityOff",
    "visibility_off_rounded":     "visibilityOff",
    "visibility_off":             "visibilityOff",
    "visibility_outlined":        "visibility",
    "visibility_rounded":         "visibilityFill",
    "visibility":                 "visibility",
    "preview_outlined":           "visibility",
    # Topic / category / label
    "topic_outlined":             "topic",
    "topic_rounded":              "topic",
    "topic":                      "topic",
    "category_outlined":          "topic",
    "category_rounded":           "topic",
    "category":                   "topic",
    "label_outlined":             "label",
    "label_rounded":              "label",
    "label_important_outline":    "label",
    "label":                      "label",
    "new_label_outlined":         "label",
    # Poll / chart
    "poll_outlined":              "poll",
    "poll_rounded":               "poll",
    "poll":                       "poll",
    "bar_chart_outlined":         "barChart",
    "bar_chart_rounded":          "barChart",
    "bar_chart":                  "barChart",
    "show_chart_rounded":         "trendingUp",
    "show_chart":                 "trendingUp",
    "insights":                   "insights",
    "trending_up_rounded":        "trendingUp",
    "trending_up":                "trendingUp",
    "trending_down_rounded":      "trendingDown",
    "trending_down":              "trendingDown",
    # Community / social
    "waving_hand_rounded":        "wavingHandFill",
    "waving_hand":                "waving",
    "handshake_outlined":         "handshake",
    "handshake":                  "handshake",
    "volunteer_activism_rounded": "volunteerActivismFill",
    "volunteer_activism":         "volunteerActivism",
    "campaign_outlined":          "campaign",
    "campaign":                   "campaign",
    "diversity_1":                "diversity",
    "diversity_2":                "diversity",
    "diversity_3":                "diversity",
    "how_to_vote_outlined":       "howToVote",
    "how_to_vote":                "howToVote",
    "how_to_reg_outlined":        "verifiedUser",
    # Sentiment / emoji
    "sentiment_dissatisfied_outlined": "sentimentBad",
    "sentiment_dissatisfied":     "sentimentBad",
    "sentiment_very_dissatisfied": "sentimentBad",
    "sentiment_satisfied_alt_outlined": "emoji",
    "sentiment_satisfied_alt":    "emoji",
    "emoji_emotions_outlined":    "emoji",
    "emoji_emotions":             "emoji",
    "emoji_events_outlined":      "emojiEvents",
    "emoji_events":               "emojiEvents",
    "emoji_people_outlined":      "waving",
    "emoji_people":               "waving",
    # Medical / health
    "local_hospital_outlined":    "medical",
    "local_hospital":             "medical",
    "medical_services_outlined":  "medical",
    "medical_services":           "medical",
    "medication_outlined":        "medical",
    "medication":                 "medical",
    "coronavirus_outlined":       "medical",
    "psychology_alt_outlined":    "psychology",
    "psychology_rounded":         "psychology",
    "psychology_outlined":        "psychology",
    "psychology":                 "psychology",
    "self_improvement_rounded":   "wellness",
    "self_improvement":           "wellness",
    "spa_outlined":               "spa",
    "spa":                        "spa",
    "fitness_center_outlined":    "fitness",
    "fitness_center":             "fitness",
    "accessibility_new_rounded":  "accessibility",
    "accessibility_new":          "accessibility",
    "accessibility_outlined":     "accessibility",
    "accessibility":              "accessibility",
    "wheelchair_pickup_outlined": "accessibility",
    "sign_language":              "signLanguage",
    "pregnant_woman_outlined":    "pregnant",
    "pregnant_woman":             "pregnant",
    "family_restroom":            "family",
    "child_friendly":             "childFriendly",
    "child_care_outlined":        "childCare",
    "child_care":                 "childCare",
    "baby_changing_station":      "baby",
    # Food / lifestyle
    "restaurant_outlined":        "restaurant",
    "restaurant_menu_outlined":   "restaurant",
    "restaurant":                 "restaurant",
    "lunch_dining":               "food",
    "outdoor_grill":              "grill",
    "no_food":                    "close",
    "coffee_outlined":            "coffee",
    "free_breakfast":             "coffee",
    "coffee":                     "coffee",
    "local_cafe_outlined":        "coffee",
    "local_cafe":                 "coffee",
    "local_dining_outlined":      "food",
    "local_dining":               "food",
    "fastfood_outlined":          "food",
    "fastfood":                   "food",
    "bakery_dining":              "food",
    "brunch_dining":              "food",
    "cake_outlined":              "food",
    "cake":                       "food",
    "park_outlined":              "park",
    "park_rounded":               "park",
    "park":                       "park",
    "eco_outlined":               "eco",
    "eco":                        "eco",
    "forest_outlined":            "tree",
    "nature_outlined":            "tree",
    "grass":                      "eco",
    "water_rounded":              "pool",
    "pool":                       "pool",
    # Sports / activity
    "sports_outlined":            "sports",
    "sports_golf_rounded":        "golf",
    "sports_golf":                "golf",
    "sports_soccer_rounded":      "soccer",
    "sports_soccer":              "soccer",
    "sports_tennis_rounded":      "tennis",
    "sports_tennis":              "tennis",
    "sports_basketball_rounded":  "sports",
    "sports_basketball":          "sports",
    "sports_gymnastics":          "gymnastics",
    "sports_esports_outlined":    "sports",
    "sports":                     "sports",
    "stadium_outlined":           "sports",
    "stadium":                    "sports",
    # Children / family
    "backpack_outlined":          "backpack",
    "backpack_rounded":           "backpack",
    "backpack":                   "backpack",
    "toys":                       "toys",
    "extension_outlined":         "extension",
    "extension":                  "extension",
    "chair_outlined":             "chair",
    "chair":                      "chair",
    "checkroom_outlined":         "wardrobe",
    "checkroom":                  "wardrobe",
    # Education
    "school_outlined":            "school",
    "school_rounded":             "school",
    "school":                     "school",
    "local_library_outlined":     "books",
    "local_library":              "books",
    "book_outlined":              "books",
    "book":                       "books",
    "auto_stories":               "books",
    "class_outlined":             "school",
    "class":                      "school",
    # AI / tech
    "auto_awesome_outlined":      "ai",
    "auto_awesome_motion_outlined": "ai",
    "auto_awesome_mosaic_outlined": "ai",
    "auto_awesome_rounded":       "ai",
    "auto_awesome":               "ai",
    "auto_fix_high_outlined":     "ai",
    "auto_fix_normal_outlined":   "ai",
    "auto_fix_high":              "ai",
    "auto_fix_off":               "ai",
    "smart_toy_outlined":         "robot",
    "smart_toy_rounded":          "robot",
    "smart_toy":                  "robot",
    "memory_rounded":             "storage",
    "developer_board_outlined":   "storage",
    "wifi_outlined":              "wifi",
    "wifi_off_rounded":           "wifiOff",
    "wifi_off":                   "wifiOff",
    "wifi_rounded":               "wifi",
    "wifi":                       "wifi",
    "bluetooth_rounded":          "wifi",
    "bluetooth":                  "wifi",
    "phone_android_rounded":      "phoneDevice",
    "phone_android":              "phoneDevice",
    "phone_iphone":               "phoneDevice",
    "laptop_mac_outlined":        "laptopMac",
    "laptop_mac":                 "laptopMac",
    "laptop_outlined":            "laptop",
    "laptop":                     "laptop",
    "computer_outlined":          "laptop",
    "computer":                   "laptop",
    "devices_rounded":            "phoneDevice",
    "devices":                    "phoneDevice",
    # Achievements / status
    "workspace_premium_outlined": "premium",
    "workspace_premium":          "premiumFill",
    "military_tech_outlined":     "medal",
    "military_tech":              "medal",
    "emoji_events":               "emojiEvents",
    "stars_rounded":              "starFill",
    "stars":                      "starFill",
    "history_toggle_off_rounded": "history",
    "history_rounded":            "history",
    "history":                    "history",
    # Payments / subscriptions
    "confirmation_number_outlined": "ticket",
    "confirmation_number":        "ticket",
    "redeem_outlined":            "ticket",
    "redeem":                     "ticket",
    "pending_rounded":            "pending",
    "pending_outlined":           "pending",
    "pending":                    "pending",
    # Admin / moderation
    "admin_panel_settings_outlined": "adminPanel",
    "admin_panel_settings":       "adminPanel",
    "support_agent_outlined":     "support",
    "support_agent":              "support",
    "support_outlined":           "support",
    "headset_mic_outlined":       "support",
    "headset_outlined":           "support",
    "headset":                    "support",
    "summarize_outlined":         "summarize",
    "summarize_rounded":          "summarize",
    "summarize":                  "summarize",
    "gavel_outlined":             "gavel",
    "gavel_rounded":              "gavel",
    "gavel":                      "gavel",
    "balance_outlined":           "balance",
    "balance":                    "balance",
    "policy_outlined":            "shield",
    "policy":                     "shield",
    "rule_outlined":              "checklist",
    "rule":                       "checklist",
    # Misc / UI
    "nightlight_round":           "nightMode",
    "bedtime_outlined":           "bedtime",
    "bedtime_off_outlined":       "close",
    "bedtime":                    "bedtime",
    "light_mode_outlined":        "flash",
    "dark_mode_outlined":         "nightMode",
    "brightness_6_outlined":      "flash",
    "flash_on_rounded":           "flash",
    "flash_off_rounded":          "flash",
    "flash_on":                   "flash",
    "bolt_rounded":               "flash",
    "bolt":                       "flash",
    "all_inclusive_rounded":      "allInclusive",
    "all_inclusive":              "allInclusive",
    "layers_outlined":            "layers",
    "layers_clear":               "layers",
    "layers":                     "layers",
    "palette_outlined":           "palette",
    "palette":                    "palette",
    "color_lens_outlined":        "palette",
    "color_lens":                 "palette",
    "brush_outlined":             "brush",
    "brush":                      "brush",
    "rocket_launch_outlined":     "rocket",
    "rocket_launch":              "rocket",
    "rocket_rounded":             "rocket",
    "rocket":                     "rocket",
    "lightbulb_outline_rounded":  "lightbulb",
    "lightbulb_outline":          "lightbulb",
    "lightbulb_outlined":         "lightbulb",
    "lightbulb_rounded":          "lightbulbFill",
    "lightbulb":                  "lightbulb",
    "emoji_objects_outlined":     "lightbulb",
    "tips_and_updates_outlined":  "lightbulb",
    "inbox_outlined":             "inbox",
    "inbox":                      "inbox",
    "print_outlined":             "print",
    "print":                      "print",
    "qr_code_scanner":            "camera",
    "qr_code_2":                  "camera",
    "qr_code":                    "camera",
    "apps_rounded":               "gridView",
    "apps":                       "gridView",
    "reorder":                    "listView",
    "subject":                    "listView",
    "keyboard_outlined":          "edit",
    "keyboard_hide":              "close",
    "keyboard":                   "edit",
    "input_rounded":              "forward",
    "input":                      "forward",
    "output_rounded":             "arrowForward",
    "north_west":                 "northWest",
    "north_outlined":             "northDir",
    "north":                      "northDir",
    "south_outlined":             "southDir",
    "south":                      "southDir",
    "east":                       "arrowForward",
    "west":                       "arrowBack",
    "subdirectory_arrow_right_rounded": "subArrowRight",
    "subdirectory_arrow_right":   "subArrowRight",
    "shortcut_rounded":           "shortcut",
    "shortcut":                   "shortcut",
    "swap_horiz_rounded":         "arrowForward",
    "swap_horiz":                 "arrowForward",
    "fiber_new":                  "fiberNew",
    "g_mobiledata":               "gMobiledata",
    "theater_comedy_outlined":    "theater",
    "theater_comedy":             "theater",
    "celebration_rounded":        "celebration",
    "celebration":                "celebration",
    "man_rounded":                "man",
    "man":                        "man",
    "recycle_outlined":           "recycle",
    "recycle":                    "recycle",
    "contact_emergency_outlined": "user",
    "contacts_outlined":          "contacts",
    "import_export_rounded":      "arrowUp",
    "exit_to_app_rounded":        "exitToApp",
    "exit_to_app":                "exitToApp",
    "logout_rounded":             "logout",
    "logout":                     "logout",
    "login_rounded":              "arrowForward",
    "login":                      "arrowForward",
    "meeting_room_outlined":      "usersThree",
    "reduce_capacity_outlined":   "usersThree",
    "location_city_outlined":     "business",
    "local_atm":                  "money",
    "paid_outlined":              "payment",
    "paid":                       "payment",
    "currency_pound":             "money",
    "currency_exchange":          "refresh",
    "price_change_outlined":      "trendingUp",
    "price_change":               "trendingUp",
    "price_check_outlined":       "checkCircle",
    # Additional specific Material icons
    "fiber_manual_record_rounded": "record",
    "lens_outlined":              "circle",
    "lens":                       "circleFill",
    "radio_button_unchecked_rounded": "radioOff",
    "adjust":                     "radioOnFill",
    "brightness_1":               "circleFill",
    "crop_square":                "checkSquare",
    "crop_landscape":             "image",
    "aspect_ratio":               "image",
    "fullscreen_rounded":         "arrowSquareOut",
    "fullscreen_exit_rounded":    "close",
    "fullscreen":                 "openInNew",
    "open_with":                  "arrowUp",
    "drag_handle":                "moreHoriz",
    "drag_indicator":             "moreVert",
    "unfold_more_rounded":        "caretDown",
    "unfold_less_rounded":        "caretUp",
    "unfold_more":                "caretDown",
    "unfold_less":                "caretUp",
    "first_page":                 "arrowBack",
    "last_page":                  "arrowForward",
    "skip_previous_rounded":      "arrowBack",
    "skip_next_rounded":          "arrowForward",
    "navigate_before_rounded":    "caretLeft",
    "navigate_next_rounded":      "caretRight",
}

# CupertinoIcons → HuddlIcons mapping
CUPERTINO_MAP = {
    "back":                       "arrowBack",
    "back_solid":                 "arrowBack",
    "forward":                    "arrowForward",
    "chevron_back":               "arrowBack",
    "chevron_forward":            "arrowForward",
    "chevron_left":               "caretLeft",
    "chevron_left_bold":          "caretLeft",
    "chevron_right":              "caretRight",
    "chevron_right_bold":         "caretRight",
    "chevron_up":                 "caretUp",
    "chevron_down":               "caretDown",
    "left_chevron":               "caretLeft",
    "right_chevron":              "caretRight",
    "up_arrow":                   "arrowUp",
    "down_arrow":                 "arrowDown",
    "arrow_up":                   "arrowUp",
    "arrow_down":                 "arrowDown",
    "arrow_left":                 "arrowBack",
    "arrow_right":                "arrowForward",
    "arrow_up_circle":            "addCircle",
    "arrow_up_circle_fill":       "addCircleFill",
    "arrow_down_circle":          "caretDown",
    "arrow_down_circle_fill":     "caretDown",
    "arrow_uturn_left":           "reply",
    "arrow_turn_up_left":         "reply",
    "person":                     "user",
    "person_fill":                "userFill",
    "person_add":                 "personAdd",
    "person_add_solid":           "personAdd",
    "person_crop_circle":         "user",
    "person_crop_circle_fill":    "userFill",
    "person_2":                   "users",
    "person_2_fill":              "usersThreeFill",
    "person_3":                   "usersThree",
    "person_3_fill":              "usersThreeFill",
    "group":                      "usersThree",
    "group_solid":                "usersThreeFill",
    "bookmark":                   "bookmark",
    "bookmark_fill":              "bookmarkFill",
    "bookmark_solid":             "bookmarkFill",
    "heart":                      "heart",
    "heart_fill":                 "heartFill",
    "heart_solid":                "heartFill",
    "star":                       "star",
    "star_fill":                  "starFill",
    "star_solid":                 "starFill",
    "hand_thumbsup":              "thumbUp",
    "hand_thumbsup_fill":         "thumbUpFill",
    "hand_thumbsdown":            "thumbDown",
    "hand_thumbsdown_fill":       "thumbDownFill",
    "chat_bubble":                "chat",
    "chat_bubble_fill":           "chatFill",
    "chat_bubble_2":              "forum",
    "chat_bubble_2_fill":         "forum",
    "chat_bubble_text":           "chatDots",
    "chat_bubble_text_fill":      "chatDots",
    "paperplane":                 "send",
    "paperplane_fill":            "sendFill",
    "reply":                      "reply",
    "share":                      "share",
    "share_solid":                "share",
    "phone":                      "phone",
    "phone_fill":                 "phone",
    "phone_badge_plus":           "phone",
    "envelope":                   "email",
    "envelope_fill":              "emailFill",
    "envelope_open":              "email",
    "envelope_open_fill":         "emailFill",
    "bell":                       "bell",
    "bell_fill":                  "bellFill",
    "bell_solid":                 "bellFill",
    "bell_slash":                 "bellSlash",
    "bell_slash_fill":            "bellSlash",
    "clock":                      "clock",
    "clock_fill":                 "clockFill",
    "clock_solid":                "clockFill",
    "timer":                      "alarm",
    "calendar":                   "calendar",
    "calendar_badge_plus":        "calendarPlus",
    "calendar_badge_minus":       "calendarX",
    "calendar_circle":            "calendar",
    "calendar_circle_fill":       "calendarFill",
    "calendar_today":             "calendar",
    "magnifyingglass":            "search",
    "magnifyingglass_circle":     "search",
    "magnifyingglass_circle_fill": "search",
    "house":                      "home",
    "house_fill":                 "homeFill",
    "house_solid":                "homeFill",
    "map":                        "map",
    "map_fill":                   "map",
    "map_pin":                    "locationPin",
    "map_pin_ellipse":            "locationPinFill",
    "location":                   "locationPin",
    "location_fill":              "locationPinFill",
    "location_solid":             "locationPinFill",
    "compass":                    "explore",
    "compass_fill":               "explore",
    "pencil":                     "edit",
    "pencil_circle":              "edit",
    "pencil_circle_fill":         "edit",
    "pencil_slash":               "close",
    "square_and_pencil":          "edit",
    "info":                       "info",
    "info_circle":                "info",
    "info_circle_fill":           "infoFill",
    "exclamationmark":            "priority",
    "exclamationmark_circle":     "error",
    "exclamationmark_circle_fill": "errorFill",
    "exclamationmark_triangle":   "warning",
    "exclamationmark_triangle_fill": "warningFill",
    "checkmark":                  "check",
    "checkmark_circle":           "checkCircle",
    "checkmark_circle_fill":      "checkCircleFill",
    "checkmark_square":           "checkSquareFill",
    "checkmark_seal":             "verified",
    "checkmark_seal_fill":        "verifiedFill",
    "xmark":                      "close",
    "xmark_circle":               "cancel",
    "xmark_circle_fill":          "cancel",
    "plus":                       "add",
    "plus_circle":                "addCircle",
    "plus_circle_fill":           "addCircleFill",
    "minus":                      "remove",
    "minus_circle":               "removeCircle",
    "minus_circle_fill":          "removeCircle",
    "ellipsis":                   "moreHoriz",
    "ellipsis_horizontal":        "moreHoriz",
    "ellipsis_vertical":          "moreVert",
    "ellipsis_circle":            "moreHoriz",
    "list_bullet":                "listView",
    "list_dash":                  "listView",
    "list_number":                "listView",
    "grid":                       "gridView",
    "slider_horizontal_3":        "filter",
    "arrow_up_arrow_down":        "sortAscending",
    "arrow_clockwise":            "refresh",
    "arrow_counterclockwise":     "redo",
    "externallinkImage":          "openInNew",
    "link":                       "link",
    "pin":                        "pin",
    "pin_fill":                   "pinFill",
    "trash":                      "delete",
    "trash_fill":                 "deleteFill",
    "trash_slash":                "delete",
    "gear":                       "settings",
    "gear_alt":                   "settings",
    "gear_alt_fill":              "settingsFill",
    "globe":                      "language",
    "eye":                        "visibility",
    "eye_fill":                   "visibilityFill",
    "eye_slash":                  "visibilityOff",
    "eye_slash_fill":             "visibilityOff",
    "tag":                        "sellTag",
    "tag_fill":                   "sellTagFill",
    "flag":                       "flag",
    "flag_fill":                  "flagFill",
    "chart_bar":                  "barChart",
    "chart_bar_fill":             "barChartFill",
    "waveform":                   "mic",
    "mic":                        "mic",
    "mic_fill":                   "micFill",
    "mic_slash":                  "micOff",
    "mic_slash_fill":             "micOff",
    "play":                       "play",
    "play_fill":                  "playFill",
    "play_circle":                "playCircle",
    "play_circle_fill":           "playFill",
    "pause":                      "pause",
    "pause_fill":                 "pause",
    "stop":                       "stop",
    "stop_fill":                  "stop",
    "camera":                     "camera",
    "camera_fill":                "camera",
    "photo":                      "image",
    "photo_fill":                 "image",
    "photo_on_rectangle":         "photoLibrary",
    "photo_on_rectangle_fill":    "photoLibraryFill",
    "video_camera":               "videocam",
    "video_camera_fill":          "videocam",
    "lock":                       "lock",
    "lock_fill":                  "lockFill",
    "lock_open":                  "lockOpen",
    "lock_open_fill":             "lockOpen",
    "shield":                     "shield",
    "shield_fill":                "shieldFill",
    "shield_slash":               "close",
    "hand_raised":                "block",
    "hand_raised_fill":           "block",
    "car":                        "work",
    "car_fill":                   "work",
    "cloud":                      "cloud",
    "cloud_fill":                 "cloud",
    "cloud_upload":               "cloudUpload",
    "cloud_upload_fill":          "cloudUpload",
    "cloud_download":             "download",
    "tray_arrow_up":              "upload",
    "tray_arrow_down":            "download",
    "square_and_arrow_up":        "share",
    "square_and_arrow_up_fill":   "share",
    "square_and_arrow_down":      "download",
    "doc":                        "file",
    "doc_fill":                   "file",
    "doc_text":                   "description",
    "doc_text_fill":              "description",
    "doc_on_clipboard":           "assignment",
    "star_circle":                "starFill",
    "star_circle_fill":           "starFill",
    "rosette":                    "medal",
    "sportscourt":                "sports",
    "sportscourt_fill":           "sports",
    "gift":                       "celebration",
    "gift_fill":                  "celebration",
    "sun_max":                    "flash",
    "sun_max_fill":               "flash",
    "moon":                       "nightMode",
    "moon_fill":                  "nightMode",
    "bolt":                       "flash",
    "bolt_fill":                  "flash",
    "lightbulb":                  "lightbulb",
    "lightbulb_fill":             "lightbulbFill",
    "wand_and_stars":             "ai",
    "wand_and_stars_inverse":     "ai",
    "cpu":                        "storage",
    "wifi":                       "wifi",
    "wifi_slash":                 "wifiOff",
    "ant":                        "settings",
    "ant_fill":                   "settings",
    "creditcard":                 "creditCard",
    "creditcard_fill":            "creditCard",
    "bag":                        "shoppingBag",
    "bag_fill":                   "shoppingBag",
    "cart":                       "shoppingBag",
    "cart_fill":                  "shoppingBag",
    "storefront":                 "storefront",
    "storefront_fill":            "storefrontFill",
    "building_2":                 "business",
    "building_2_fill":            "business",
    "briefcase":                  "work",
    "briefcase_fill":             "workFill",
    "graduationcap":              "school",
    "graduationcap_fill":         "school",
    "book":                       "books",
    "book_fill":                  "books",
    "books_vertical":             "books",
    "books_vertical_fill":        "books",
    "newspaper":                  "article",
    "newspaper_fill":             "article",
    "bubble_left":                "chat",
    "bubble_left_fill":           "chatFill",
    "bubble_right":               "chat",
    "bubble_right_fill":          "chatFill",
    "bubble_middle_bottom":       "chatDots",
    "bolt_heart":                 "heartFill",
    "bolt_heart_fill":            "heartFill",
    "hand_tap":                   "waving",
    "wave_3_right":               "waving",
    "keyboard":                   "edit",
    "keyboard_chevron_compact_down": "close",
    "signature":                  "edit",
    "pencil_outline":             "edit",
    "return":                     "reply",
    "escape":                     "close",
    "delete_left":                "close",
    "delete_right":               "close",
    "arrow_up_left":              "arrowBack",
    "arrow_up_right":             "openInNew",
    "arrow_down_left":            "arrowBack",
    "arrow_down_right":           "arrowForward",
    "command":                    "settings",
    "option":                     "settings",
    "rectangle_and_pencil_and_ellipsis": "edit",
    "sidebar_left":               "menu",
    "sidebar_right":              "menu",
    "list_bullet_rectangle":      "listView",
    "square_grid_2x2":            "gridView",
    "rectangle_grid_1x2":         "listView",
    "text_justify":               "listView",
    "arrow_merge":                "forward",
    "arrow_split":                "forward",
}

# Files to skip entirely (test files etc.)
SKIP_FILES = {
    "lib/theme/huddl_icons.dart",
    "lib/widgets/huddl_category_icon.dart",
}

# ── IMPORT MANAGEMENT ────────────────────────────────────────────────────────
HUDDL_IMPORT = "import '../theme/huddl_icons.dart';"
MATERIAL_IMPORT_PATTERN = re.compile(r"^import 'package:flutter/material\.dart';", re.MULTILINE)
CUPERTINO_IMPORT_PATTERN = re.compile(r"^import 'package:flutter/cupertino\.dart';", re.MULTILINE)

def _relative_import(file_path: Path, project_root: Path) -> str:
    """Generate correct relative import path based on file depth in lib/."""
    rel = file_path.relative_to(project_root / "lib")
    depth = len(rel.parts) - 1  # depth below lib/
    prefix = "../" * depth
    if depth == 0:
        prefix = "./"
    return f"import '{prefix}theme/huddl_icons.dart';"


# ── REGEX PATTERNS ────────────────────────────────────────────────────────────
# Match Icons.xxx — stops at word boundary, handles trailing commas/parens
# We sort keys by length descending so longer keys match first
SORTED_ICON_KEYS = sorted(ICONS_MAP.keys(), key=len, reverse=True)
SORTED_CUPERTINO_KEYS = sorted(CUPERTINO_MAP.keys(), key=len, reverse=True)

def build_icons_pattern():
    keys = "|".join(re.escape(k) for k in SORTED_ICON_KEYS)
    return re.compile(r"\bIcons\.(" + keys + r")\b")

def build_cupertino_pattern():
    keys = "|".join(re.escape(k) for k in SORTED_CUPERTINO_KEYS)
    return re.compile(r"\bCupertinoIcons\.(" + keys + r")\b")

# Fallback — catch any remaining Icons.xxx or CupertinoIcons.xxx not in map
ICONS_UNKNOWN_PATTERN = re.compile(r"\bIcons\.([a-zA-Z0-9_]+)\b")
CUPERTINO_UNKNOWN_PATTERN = re.compile(r"\bCupertinoIcons\.([a-zA-Z0-9_]+)\b")


def process_file(path: Path, project_root: Path, report: dict) -> bool:
    """Process a single dart file. Returns True if any changes were made."""
    rel_path = str(path.relative_to(project_root))
    if rel_path in SKIP_FILES:
        return False

    original = path.read_text(encoding="utf-8")
    text = original

    icons_pat = build_icons_pattern()
    cupertino_pat = build_cupertino_pattern()

    replacements_made = 0

    # 1. Replace known Icons.xxx
    def replace_icon(m):
        nonlocal replacements_made
        huddl = ICONS_MAP[m.group(1)]
        replacements_made += 1
        report.setdefault("replaced", []).append(f"{rel_path}: Icons.{m.group(1)} → HuddlIcons.{huddl}")
        return f"HuddlIcons.{huddl}"

    text = icons_pat.sub(replace_icon, text)

    # 2. Replace known CupertinoIcons.xxx
    def replace_cupertino(m):
        nonlocal replacements_made
        huddl = CUPERTINO_MAP[m.group(1)]
        replacements_made += 1
        report.setdefault("replaced", []).append(f"{rel_path}: CupertinoIcons.{m.group(1)} → HuddlIcons.{huddl}")
        return f"HuddlIcons.{huddl}"

    text = cupertino_pat.sub(replace_cupertino, text)

    # 3. Flag any remaining unknown Icons.xxx
    unknowns = ICONS_UNKNOWN_PATTERN.findall(text)
    for u in unknowns:
        if u not in ("fromList",):  # skip false positives
            report.setdefault("unknown", []).append(f"{rel_path}: Icons.{u} — NOT IN MAP")

    # 4. Flag any remaining unknown CupertinoIcons.xxx
    c_unknowns = CUPERTINO_UNKNOWN_PATTERN.findall(text)
    for u in c_unknowns:
        report.setdefault("unknown", []).append(f"{rel_path}: CupertinoIcons.{u} — NOT IN MAP")

    if text == original:
        return False

    # 5. Add import if needed
    huddl_import = _relative_import(path, project_root)
    if "huddl_icons.dart" not in text:
        # Insert after first import line
        first_import = text.find("import ")
        if first_import >= 0:
            line_end = text.find("\n", first_import)
            text = text[:line_end + 1] + huddl_import + "\n" + text[line_end + 1:]
        else:
            text = huddl_import + "\n" + text

    path.write_text(text, encoding="utf-8")
    return True


def main():
    project_root = Path("/home/user/flutter_app")
    lib_dir = project_root / "lib"

    dart_files = list(lib_dir.rglob("*.dart"))
    print(f"Found {len(dart_files)} dart files in lib/")

    report = {}
    changed = 0
    unchanged = 0

    for f in sorted(dart_files):
        if process_file(f, project_root, report):
            changed += 1
            print(f"  ✓ {f.relative_to(project_root)}")
        else:
            unchanged += 1

    print(f"\n{'='*60}")
    print(f"Changed : {changed} files")
    print(f"Unchanged: {unchanged} files")

    replaced = report.get("replaced", [])
    unknown = report.get("unknown", [])

    print(f"\nReplaced: {len(replaced)} call-sites")
    if unknown:
        print(f"\n⚠️  UNMAPPED (require manual review): {len(unknown)}")
        for u in unknown:
            print(f"   {u}")
    else:
        print("\n✅  No unmapped icons — all call-sites resolved.")

    # Write full report
    report_path = project_root / "icon_replacement_report.txt"
    with open(report_path, "w") as f:
        f.write(f"Icon Replacement Report\n{'='*60}\n\n")
        f.write(f"Files changed: {changed}\n")
        f.write(f"Files unchanged: {unchanged}\n")
        f.write(f"Call-sites replaced: {len(replaced)}\n\n")
        if unknown:
            f.write(f"UNMAPPED ICONS ({len(unknown)}) — require manual review:\n")
            for u in unknown:
                f.write(f"  {u}\n")
            f.write("\n")
        f.write(f"ALL REPLACEMENTS ({len(replaced)}):\n")
        for r in replaced[:200]:  # first 200 for brevity
            f.write(f"  {r}\n")
        if len(replaced) > 200:
            f.write(f"  ... and {len(replaced) - 200} more\n")
    print(f"\nFull report written to: {report_path}")


if __name__ == "__main__":
    main()
